CommonPrayersArray= [[
[
Prefix.commonPrayer+"OurFatherWhoArtInHeaven&D=$copticFeasts.AnyDay&C=SubTitle", 
"", 
"Notre Père qui es aux cieux", 
"", 
" أبَانَا الذي في السَّمَواتْ", 
],
[
Prefix.same+"&C=Assembly", 
"Ϫⲉ Ⲡⲉⲛⲓⲱⲧ ⲉⲧ ⲯⲉⲛ ⲛⲓⲫϩⲟⲩⲓ̀, ⲙⲁⲣⲉϥⲧⲟⲩⲃⲟ ⲛ̀ϫⲉ ⲡⲉⲕⲣⲁⲛ, ⲙⲁⲣⲉⲥⲓ̀ ⲛ̀ϫⲉ ⲧⲉⲕⲙⲉⲧⲟⲩⲣⲟ, ⲡⲉⲧⲉⳣⲛⲁⲕ ⲙⲁⲣⲉϥϯⲱⲡⲓ ⲙ̀ⲫ̀ⲣϩ ̀ⲯⲉⲛ ⲧ̀ⲫⲉ ⲛⲉⲙ ⳣⲓϫⲉⲛ ⲡⲓⲕⲁⳣ,", 
"Notre Père qui es aux cieux, Que Ton Nom soit sanctifié. Que Ton règne vienne. Que Ta volonté soit faite sur la terre comme au ciel.", 
"جي بنيوت إتخين نيفيئوي ماريفطوفو أنجي بيكران. ماريسئي إنجي تيكميتؤرو. بيتهيناك ماريف شوبي إم إفريتي خين أتفي نيم هيجين بي كاهي.", 
"أبَانَا الذي في السَّمَواتْ، ليَتَقَدَّسْ اسمك، لِيأتْ مَلَكُوتَكْ. لِتَكُنْ مَشِيئَتُكْ كما في السَّمَاء كذلك على الأرْضَ.", 
],
[
Prefix.same+"&C=Assembly", 
"ⲡⲉⲛⲱⲓⲕ ⲛ̀ⲧⲉ ⲣⲁⲥ ̀ⲙϩⲓϥ ⲛⲁⲛ ⲙ̀ⲫⲟⲟⲩ, ⲟⲩⲟⳣ ⲝⲁ ⲛϩⲉ̀ⲧⲉⲣⲟⲛ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ, ⲙ̀ⲫ̀ⲣϩ ̀ⳣⲱⲛ ⲛ̀ⲧⲉⲛⲝⲱ ⲉ̀ⲃⲟⲗⲛ̀ⲛϩⲉ̀ⲧⲉ ⲟⲩⲟⲛ ⲛ̀ⲧⲁⲛ ⲉ̀ⲣⲱⲟⲩ, ⲟⲩⲟⳣ ⲙ̀ⲡⲉⲣⲉⲛⲧⲉⲛ ⲉ̀ⲯⲟⲩⲛ ⲉ̀ⲡⲓⲣⲁⲥⲙⲟⲥ, ⲁⲗⲗⲁ ⲛⲁⳣⲙⲉⲛ ⲉ̀ⲃⲟⲗⳣⲁ ⲡⲓⲡⲉⲧⳣⲱⲟⲩ, ⲯⲉⲛ Ⲡⲓⲝ̀ⲣⲓⲥⲧⲟⲥ Ⲓϩⲥⲟⲩⲥ Ⲡⲉⲛϣⲟⲓⲥ.", 
"Donne-nous aujourd’hui notre pain de ce jour; pardonne-nous nos offenses, comme nous pardonnons aussi à ceux qui nous ont offensés; ne nous soumets pas à la tentation, mais délivre-nous du mal, par le Christ Jésus, Notre Seigneur, car c’est à Toi qu’appartiennent le règne, la puissance et la gloire dans les siècles des siècles. Amen.", 
"بين أويك إنتي راستي ميف نان إمفوؤو أووه كانيئتيرون نان إيفول إم إفريتي هون إنتين كو إيفول إن نيئتي أوؤن إنتان إيرؤو. أووه إمبير إنتين إيخون إى بي راموس. أللا ناهمين إيفول هابي بيتهوؤو خين بي إخرستوس إيسوس بين شويس.", 
"خبزنا الذي للغد أعطنا اليوم واغفر لنا ذنوبنا كما نغفر نحن أيضا للمذنبين إلينا. ولا تُدْخِلْنَا في تَجْرِبَة لَكِنْ نجنا من الشِرّيرْ بِالْمَسِيحْ يَسُوعْ رَبّنا.", 
],
],
[
[
Prefix.commonPrayer+"InTheNameOfJesusOurLord&D=$copticFeasts.AnyDay&C=Diacon", 
"Ϧⲉⲛ Ⲡⲭ̅ⲥ̅ Ⲓⲏ̅ⲥ̅ ⲡⲉⲛϭⲟⲓⲥ.", 
"Par le Christ Jésus notre Seigneur.", 
"خين باخريستوس بينشويس", 
"بِالْمَسِيحْ يَسُوعْ رَبّنا.", 
],
],
[
[
Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay&C=Priest", 
"Ϣ̀ⲗⲏⲗ", 
"Prions.", 
"شليل", 
"صَلّوا.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲉ̀ⲡⲓ ⲡ̀ⲣⲟⲥⲉⲩⲭⲏ ⲥ̀ⲧⲁⲑⲏⲧⲉ.", 
"Pour la prière levons-nous.", 
"إيبى إبروس إفشي إستاثيتى", 
"لِلْصَلاة قِفُوا", 
],
],
[
[
Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay&C=Priest", 
"Ⲓⲣⲏⲛⲏ ⲡⲁⲥⲓ.", 
"La paix soit avec vous.", 
"إيريني باسي", 
"السَّلامُ لِجَمِيِعِكُمْ.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"AssemblyResponseAndWithYourSoul&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"ThanksGiving&D=$copticFeasts.AnyDay&C=", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"ThanksGivingPart1&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"DiaconResponsePray&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"ThanksGivingPart2&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonIncense+"PrayThatGodHaveMercyOnUs&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"ThanksGivingPart3&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonIncense+"ThanksGivingPart3Comment&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"ThanksGivingPart1&D=$copticFeasts.AnyDay&C=SubTitle", 
"", 
"Action de grâce", 
"", 
" صَلاةْ الشكر", 
],
[
Prefix.same+"&C=Priest", 
"Ⲙⲁⲣⲉⲛϣⲉⲡϩ̀ⲙⲟⲧ ⲛ̀ⲧⲟⲧϥ ⲙ̀ⲡⲓⲣⲉϥ- ⲉⲣⲡⲉⲑⲛⲁⲛⲉϥ ⲟⲩⲟϩ ⲛ̀ⲛⲁⲏⲧ: Ⲫⲛⲟⲩϯ Ⲫⲓⲱⲧ ⲙ̀Ⲡⲉⲛϭⲟⲓⲥ ⲟⲩⲟϩ Ⲡⲉⲛⲛⲟⲩϯ ⲟⲩⲟϩ ⲡⲉⲛⲥⲱⲧⲏⲣ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅: Ϫⲉ ⲁϥⲉⲣⲥ̀ⲕⲉⲡⲁⲍⲓⲛ ⲉ̀ϫⲱⲛ: ⲁϥⲉⲣⲃⲟⲏ̀ⲑⲓⲛ ⲉ̀ⲣⲟⲛ: ⲁϥⲁ̀ⲣⲉϩ ⲉ̀ⲣⲟⲛ:", 
"Rendons grâce à Dieu le bienfaiteur et miséricordieux, Père de notre Seigneur, Dieu et Sauveur Jésus Christ, parce qu’Il nous a protégés, aidés, préservés, reçus avec bonté, traités avec miséricorde, fortifiés et fait parvenir jusqu’à cette heure.", 
"مارين شييهموت إنتوتك إنبي ريف إرَبّي ثينانيف أووه إننايت افنوتي فيوت إمبينتشويس أووه بيننوتي أووه بينسوتير إيسوس بيخريستوس. جي آفير إسكيباذين إجون آف إرفو إثين إرون آف آريه إيرون آفشوبت إن إرون آفتياسو إيرون", 
"فَلْنَشْكُرْ صانع الخَيّْرَاتْ، الرحوم اللّه، أبا رَبَّنَا وإلهَنَا ومُخَلصُنَا يَسُوعْ المسيح. لِأنَّهُ سترنا وأعاننا وحفظنا وقبلنا إليه وأشفقَ عَلَيْنَا وعضدنا وأتى بنا إلى هَذِهِ الساعة.", 
],
[
Prefix.same+"&C=Priest", 
"ⲁϥϣⲟⲡⲧⲉⲛ ⲉ̀ⲣⲟϥ ⲁϥϯⲁ̀ⲥⲟ ⲉ̀ⲣⲟⲛ: ⲁϥϯⲧⲟⲧⲉⲛ ⲁϥⲉⲛⲧⲉⲛ ϣⲁ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ⲧⲁⲓⲟⲩⲛⲟⲩ ⲑⲁⲓ. Ⲛⲑⲟϥ ⲟⲛ ⲙⲁⲣⲉⲛϯϩⲟ ⲉ̀ⲣⲟϥ ϩⲟⲡⲱⲥ ⲛ̀ⲧⲉϥⲁ̀Ϯⲣⲉϩ ⲉ̀ⲣⲟⲛ: ϧⲉⲛ ⲡⲁⲓⲉ̀ϩⲟⲟⲩ ⲉⲑⲟⲩⲁⲃ ⲫⲁⲓ ⲛⲉⲙ ⲛⲓⲉ̀ϩⲟⲟⲩ ⲧⲏⲣⲟⲩ ⲛ̀ⲧⲉ ⲡⲉⲛⲱⲛϧ: ϧⲉⲛ ϩⲓⲣⲏⲛⲏ ⲛⲓⲃⲉⲛ: ⲛ̀ϫⲉ ⲡⲓⲡⲁⲛⲧⲟⲕⲣⲁⲧⲱⲣ Ⲡϭⲟⲓⲥ Ⲡⲉⲛⲛⲟⲩϯ.", 
"Supplions-Le encore de nous garder en ce saint jour et tous les jours de notre vie en toute paix; Lui qui est Tout-Puissant, le Seigneur notre Dieu.", 
"آفتي توتين آف إنتين شا إي إهري إتآيونو ثاي ىثوف أون مارين تيهو إيروف هوبوس إنتيف آريه إيرون. خين باي إيهؤو إثؤواب خاي نيم ني إيهؤو تيروف إنتي بينؤنخ خين هيريني نيفين إنجي بي بانتوكراتور ابشويس بينوتي.", 
"هو أيضاً فلنسألهُ أنْ يحفظنا في هَذا اليوم المُقَدَّسْ وكُلَّ أيام حياتنا بِكُلَّ سَلام، ضَابِطْ الكُلّ الرَبُّ إلهُنا.", 
],
],
[
[
Prefix.commonPrayer+"DiaconResponsePray&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲡⲣⲟⲥⲉⲩⲝⲁⲥⲑⲉ.", 
"Prions.", 
"بروس إيفكساسي", 
"صلوا.", 
],
],
[
[
Prefix.commonPrayer+"ThanksGivingPart2&D=$copticFeasts.AnyDay&C=Priest", 
"Ⲫⲛⲏⲃ Ⲡϭⲟⲓⲥ Ⲫⲛⲟⲩϯ ⲡⲓⲡⲁⲛⲧⲟⲕⲣⲁⲧⲱⲣ: Ⲫⲓⲱⲧ ⲙ̀Ⲡⲉⲛϭⲟⲓⲥ ⲟⲩⲟϩ Ⲡⲉⲛⲛⲟⲩϯ ⲟⲩⲟϩ ⲡⲉⲛⲥⲱⲧⲏⲣ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅:", 
"Ô Maître Seigneur, Dieu Tout-Puissant, Père de notre Seigneur, Dieu et Sauveur Jésus-Christ, nous Te rendons grâce, de toute circonstance, pour toute circonstance et en toute circonstance.", 
"فنيف بشويس بينوتي بيبانتوكراتور افيوت إمبينشويس أووه بيننوتي أووه بينسوتير إيسوس باخرستوس. تين شيبيهموت انتوتك ناتا هوف نيفين نيم إثفو هوف نيفين نيم خين هوف نيفين.", 
"أَيُّهَااَلسيدُ الرَبُّ الإله ضَابِطْ الكُلّ أبو رَبَّنَا وإلهَنَا ومُخَلصُنا يَسُوعْ المسيح، نشكرك على كُلِّ حالٍ ومن أجل كُلِّ حالٍ وفى كُلِّ حالٍ.", 
],
[
Prefix.same+"&C=Priest", 
"ⲧⲉⲛϣⲉⲡϩ̀ⲙⲟⲧ ⲛ̀ⲧⲟⲧⲕ ⲕⲁⲧⲁ ϩⲱⲃ ⲛⲓⲃⲉⲛ ⲛⲉⲙ ⲉⲑⲃⲉ ϩⲱⲃ ⲛⲓⲃⲉⲛ ⲛⲉⲙ ϧⲉⲛ ϩⲱⲃ ⲛⲓⲃⲉⲛ. Ϫⲉ ⲁⲕⲉⲣⲥ̀ⲕⲉⲡⲁⲍⲓⲛ ⲉ̀ϫⲱⲛ: ⲁⲕⲉⲣⲃⲟⲏ̀ⲑⲓⲛ ⲉ̀ⲣⲟⲛ: ⲁⲕⲁ̀ⲣⲉϩ ⲉ̀ⲣⲟⲛ: ⲁⲕϣⲟⲡⲧⲉⲛ ⲉ̀ⲣⲟⲕ: ⲁⲕϯⲁ̀ⲥⲟ ⲉ̀ⲣⲟⲛ: ⲁⲕϯⲧⲟⲧⲉⲛ: ⲁⲕⲉⲛⲧⲉⲛ ϣⲁ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ⲧⲁⲓⲟⲩⲛⲟⲩ ⲑⲁⲓ.", 
"Parce que Tu nous as protégés, aidés, préservés, reçus avec bonté, traités avec miséricorde, fortifiés et fait parvenir jusqu’à cette heure.", 
"جي آك إر إسكيباذين إيجون آك إرفو إثين إرون آك آر إيه إرون آكشوبتين إروك آك تي آسو إرون آك تي توتين آكينتين شا إي إيري إتايونو ثاي.", 
"لأنَّكَ سَتَرْتَنَا وأَعَنْتَنَا وحفظتنا وقَبِلْتَنَا إليكَ وأشفقتَ عَلَيْنَا وعضدتنا وأتَيْتَ بنا إلى هَذِهِ السَـاعَة.", 
],
],
[
[
Prefix.commonPrayer+"ThanksGivingPart3&D=$copticFeasts.AnyDay&C=Priest", 
"Ⲉⲑⲃⲉ ⲫⲁⲓ ⲧⲉⲛϯϩⲟ ⲟⲩⲟϩ ⲧⲉⲛⲧⲱⲃϩ ⲛ̀ⲧⲉⲕ ⲙⲉⲧⲁ̀ⲅⲁⲑⲟⲥ ⲡⲓⲙⲁⲓⲣⲱⲙⲓ: ⲙⲏⲓⲥ ⲛⲁⲛ ⲉⲑⲣⲉⲛϫⲱⲕ ⲉ̀ⲃⲟⲗ ⲙ̀ⲡⲁⲓ ⲕⲉ ⲉ̀ϩⲟⲟⲩ ⲉⲑⲟⲩⲁⲃ ⲫⲁⲓ: ⲛⲉⲙ ⲛⲓⲉ̀ϩⲟⲟⲩ ⲏⲣⲟⲩ ⲛ̀ⲧⲉ ⲡⲉⲛⲱⲛϧ: ϧⲉⲛ ϩⲓⲣⲏⲛⲏ ⲛⲓⲃⲉⲛ ⲛⲉⲙ ⲧⲉⲕϩⲟϯ. Ⲫⲑⲟⲛⲟⲥ ⲛⲓⲃⲉⲛ: ⲡⲓⲣⲁⲥⲙⲟⲥ ⲛⲓⲃⲉⲛ: ⲉⲛⲉⲣⲅⲓⲁ̀ ⲛⲓⲃⲉⲛ ⲛ̀ⲧⲉ ⲡ̀ⲥⲁⲧⲁⲛⲁⲥ:", 
"Pour cela, nous implorons Ta bonté, ô Ami du genre humain, donne nous d’achever ce saint jour et tous les jours de notre vie en toute paix dans Ta crainte. Toute envie, toute tentation, toute œuvre de Satan.", 
"إثفي فاي تين تيهو أووه إنتيوفه إنتيك ميت أغاثوس، بي مايرومي ميس نان إثرينجوك إفول إمباي كي إيهو إثؤواب شاي، نيم نيهؤو إروف إنتي بينؤنخ، خين هيريني نيفين نيم تيكهوتي فثونوس نيفين، بيراسموس نيفين، إن إرجيا نيفين، إنتي إبساتاناس.", 
"من أجل هَذا نسأل ونَطْلُبْ من صلاحِكَ يا مُحِبْ الَبشَرْ امنحنا أنْ نكمل هَذا اليَوم المُقَدَّسْ وكُلَّ أيام حياتنا بِكُلَّ سَلامْ مَعَ خَوفِك. كُلِّ حسدٍ وكُلَّ تجرَبّةٍ وكُلَّ فعل الشيطان:", 
],
[
Prefix.same+"&C=Priest", 
"ⲡ̀ⲥⲟϭⲛⲓ ⲛ̀ⲧⲉ ϩⲁⲛⲣⲱⲙⲓ ⲉⲩϩⲱⲟⲩ: ⲛⲉⲙ ⲡ̀ⲧⲱⲛϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲛ̀ⲧⲉ ϩⲁⲛϫⲁϫⲓ ⲛⲏⲉⲧϩⲏⲡ ⲛⲉⲙ ⲛⲏⲉⲑⲟⲩⲱⲛϩ ⲉ̀ⲃⲟⲗ. Ⲁⲗⲓⲧⲟⲩ ⲉ̀ⲃⲟⲗϩⲁⲣⲟⲛ. Ⲛⲉⲙ ⲉ̀ⲃⲟⲗϩⲁ ⲡⲉⲕⲗⲁⲟⲥ ⲧⲏⲣϥ Ⲛⲉⲙ ⲉ̀ⲃⲟⲗϩⲁ ⲡⲁⲓ ⲙⲁ ⲉⲑⲟⲩⲁⲃ ⲛ̀ⲧⲁⲕ ⲫⲁⲓ. Ⲛⲉⲙ ⲉ̀ⲃⲟⲗϩⲁ ⲧⲁⲓⲉⲕⲕ̀ⲗⲏⲥⲓⲁ ⲫⲁⲓ.", 
"toute intrigue des hommes méchants, toute attaque des ennemis visibles et invisibles: éloigne-les de nous et de tout ton peuple et de ce lieu saint qui est à Toi et de cette église.", 
"إبسوتشي ني إنتي هانرومي هينرومي إفهؤو نيم إبتونف إن إبشوي هانجاجي نيتهويب نيم ني إثؤ أونه إيفول آليتوف إفول هارون نيم إفول ها بيكلاؤس تيرف نيم إيفول ها بايما إثؤواب إنتاك شاي نيم إفول ها تاي إي إكلَيسيا شاي.", 
"ومؤامرة الناس الأشرار وقيام الأعداء الخفيين والظاهرين، انزعها عنا، وعن سَائِرْ شَعْبُكْ، و عن مَوضعِكَ المُقدس هَذا (في بَخُورعشية) وعن هَذِه الكنيسة (في بَخُورباكر).", 
],
[
Prefix.same+"&C=Priest", 
"Ⲛⲏ ⲇⲉ ⲉⲑⲛⲁⲛⲉⲩ ⲛⲉⲙ ⲛⲏⲉ̀ⲧⲉⲣⲛⲟϥⲣⲓ ⲥⲁϩⲛⲓ ⲙ̀ⲙⲱⲟⲩ ⲛⲁⲛ: ϫⲉ ⲛ̀ⲑⲟⲕ ⲡⲉ ⲉ̀ⲧⲁⲕϯ ⲙ̀ⲡⲓⲉⲣϣⲓϣⲓ ⲛⲁⲛ: ⲉ̀ϩⲱⲙⲓ ⲉ̀ϫⲉⲛ ⲛⲓϩⲟϥ ⲛⲉⲙ ⲛⲓϭⲗⲏ: ⲛⲉⲙ ⲉ̀ϫⲉⲛ ϯϫⲟⲙ ⲧⲏⲣⲥ ⲛ̀ⲧⲉ ⲡⲓϫⲁϫⲓ.", 
"Comble-nous de tous les biens et de tous les dons convenables car c’est Toi qui nous as donné le pouvoir de fouler aux pieds les serpents, les scorpions et toute la puissance de l’ennemi.", 
"ني جي إثنانيف نيم ني إيترنوفري ساهني إممؤو نان. جي إنثوك بي إتاكتي إمبي إيرشيشي نان. إيهومي إجين نيهوف نيم نيتش لا إجون تي جوم تيرس إنتي بيجاجي.", 
"أما الصالحات والنافعات فارزقنا إياها لأنَّكَ أنتَ الذي أعطيتنا السلطان أنْ ندوس الحَيَّاتَ والعقارَبّ وكُلَّ قوة العدو.", 
],
],
[
[
Prefix.commonPrayer+"KyrieElieson&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ.", 
"Pitié Seigneur.", 
"كيريالَيسون", 
"يا رَبُّ ارحم.", 
],
],
[
[
Prefix.commonPrayer+"ThanksGivingPart4&D=$copticFeasts.AnyDay&C=Priest", 
"Ϧⲉⲛ ⲡⲓϩ̀ⲙⲟⲧ ⲛⲉⲙ ⲛⲓⲙⲉⲧϣⲉⲛϩⲏⲧ ⲛⲉⲙ ϯⲙⲉⲧⲙⲁⲓⲣⲱⲙⲓ: ⲛ̀ⲧⲉ ⲡⲉⲕⲙⲟⲛⲟⲅⲉⲛⲏⲥ ⲛ̀Ϣⲏⲣⲓ: Ⲡⲉⲛⲟ̅ⲥ̅ ⲟⲩⲟϩ Ⲡⲉⲛⲛⲟⲩϯ: ⲟⲩⲟϩ Ⲡⲉⲛⲥⲱⲧⲏⲣ Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭⲣⲓⲥⲧⲟⲥ. Ⲫⲁⲓ ⲉ̀ⲧⲉ ⲉ̀ⲃⲟⲗϩⲓⲧⲟⲧϥ ⲉ̀ⲣⲉ ⲡⲓⲱ̀ⲟⲩ ⲛⲉⲙ ⲡⲓⲧⲁⲓⲟ̀ ⲛⲉⲙ ⲡⲓⲁ̀ⲙⲁϩⲓ ⲛⲉⲙ ϯⲡ̀ⲣⲟⲥⲕⲩⲛⲏⲥⲓⲥ: ⲉⲣⲡ̀ⲣⲉⲡⲓ ⲛⲁⲕ ⲛⲉⲙⲁϥ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ ⲛ̀ⲣⲉϥⲧⲁⲛϧⲟ ⲟⲩⲟϩ ⲛ̀ⲟ̀ⲙⲟⲟⲩⲥⲓⲟⲥ ⲛⲉⲙⲁⲕ Ϯⲛⲟⲩ ⲛⲉⲙ ⲛ̀ⲥⲏⲟⲩ ⲛⲓⲃⲉⲛ ⲛⲉⲙ ϣⲁ ⲉ̀ⲛⲉϩ ⲛ̀ⲧⲉ ⲛⲓⲉ̀ⲛⲉϩ ⲧⲏⲣⲟⲩ: ⲁ̀ⲙⲏⲛ.", 
"Par la grâce, la compassion et l’amour du genre humain de Ton Fils unique notre Seigneur, notre Dieu et notre Sauveur Jésus Christ, par Qui la gloire, l’honneur, la magnificence et la prosternation Te sont dus avec Lui et le Saint-Esprit vivifiant et consubstantiel à Toi Maintenant et toujours et pour les siècles des siècles. Amen.", 
"", 
"بِالْنِعْمَة والرَآفَاتْ ومَحَبَةْ الَبشَرْ اللواتي لابْنَكَ الوَحِيد الجنس، رَبّنا وإلَهْنَا ومُخَلِصّْنَا يَسُوعْ المسيح، هذا الذي مِنْ قِبَلِهِ المَجْدُ والكَرَامَةْ والعزة  والسجود. تليق بك مَعَه ومَعَ الْرُوحْ القُدُسْ، المُحْيّي المُسَاوي لك، الآن وكُلَّ أوانْ وإلى دَهْرِ الدِهُورْ. آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"AngelsPrayer&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Louons Dieu avec les Anges", 
"", 
" فلنسبح مَعَ المَلائِكَةْ قائلين", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲙⲁⲣⲉⲛϩⲱⲥ ⲛⲉⲙ ⲛⲓⲁⲅⲅⲉⲗⲟⲥ ϫⲉ ⲟⲩⲱ̀ⲟⲩ ⲙ̀Ⲫ̀ⲛⲟⲩϯ ϧⲉⲛ ⲛⲑⲉⲧϭⲟⲥⲓ: ⲛⲉⲙ ⲟⲩϩⲓⲣⲑⲛⲑ ϩⲓϫⲉⲛ ⲡⲓⲕⲁϩⲓ: ⲛⲉⲙ ⲟⲩϯⲙⲁϯ ϧⲉⲛ ⲛⲓⲣⲱⲙⲓ. Ⲧⲉⲛϩⲱⲥ ⲉ̀ⲣⲟⲕ ⲧⲉⲛⲥ̀ⲙⲟⲩ ⲉ̀ⲣⲟⲕ: ⲧⲉⲛϣⲉⲙϣⲓ ⲙ̀ⲙⲟⲕ: ⲧⲉⲛⲟⲩⲱϣⲧ ⲙ̀ⲙⲟⲕ: ⲧⲉⲛⲟⲩⲱⲛϩ ⲛⲁⲕ ̀ⲉ̀ⲃⲟⲗ: ⲧⲉⲛⲥⲁϫⲓ ϧⲉⲛ ⲡⲉⲕⲱ̀ⲟⲩ. Ⲧⲉⲛϣⲉⲡϩ̀ⲙⲟⲧ ⲛ̀ⲧⲟⲧⲕ: ⲉⲃ̀ⲉ ⲡⲉⲕⲛⲓϣϯ ⲛ̀ⲱ̀ⲟⲩ: Ⲡ̀ϭⲟⲓⲥ Ⲡ̀ⲟⲩⲣⲟ ⲉⲧ ϩⲓϫⲉⲛ ⲛⲓⲫⲑⲟⲩⲓ̀: Ⲫ̀ⲛⲟⲩϯ Ⲫ̀ⲓⲱⲧ Ⲡⲓⲡⲁⲛⲧⲟⲕⲣⲁⲧⲱⲣ. Ⲡ̀ϭⲟⲓⲥ Ⲡ̀ϣⲑⲣⲓ ⲙ̀ⲙⲁⲩⲁⲧϥ ⲡⲓⲙⲟⲛⲟⲅⲉⲛⲑⲥ Ⲓⲑⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲟ̀ⲩⲁⲃ.", 
"Louons Dieu avec les anges en disant: gloire à Dieu au plus haut des cieux, paix sur terre et joie aux hommes. Nous te louons, nous te bénissons, nous te servons, nous nous prosternons devant toi, nous Te confessons, nous Te glorifions, nous Te rendons grâce pour Ton immense gloire. Seigneur, Roi des cieux, Dieu le Père Tout-Puissant. Seigneur Fils unique Jésus Christ avec le Saint Esprit.", 
"مارين هوس نيم ني أنجيلوس", 
"فلنسبح مَعَ المَلائِكَةْ قائلين: المَجْدُ لله في الأعالي وعلى الأرْضْ السَّلامُ وفى الناس المسرة نسبحك. نباركك. نخدمك. نسجد لك. نعترف لك. ننطق بمجدك. نشكرك من أجل عظم مجدك، أيُّهَا الرَبّ المالك على السَّمَواتْ، اللّه الآب ضَابِطْ الكُلّ، والرَبّ الابْنِ الواحد الوَحِيد يَسُوعْ المسيح، والْرُوحْ القُدُسْ.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲡ̀ϭⲟⲓⲥ Ⲫ̀ⲛⲟⲩϯ Ⲡⲓϩⲑⲓⲃ ⲛ̀ⲧⲉ Ⲫ̀ⲛⲟⲩϯ: Ⲡⲓϣⲑⲣⲓ ⲛ̀ⲧⲉ Ⲫ̀ⲓⲱⲧ: ⲫⲑⲉⲧⲱ̀ⲗⲓ ⲙ̀ⲫ̀ⲛⲟⲃⲓ ⲛ̀ⲧⲉ ⲡⲓⲕⲟⲥⲙⲟⲥ ⲛⲁⲓ ⲛⲁⲛ. Ⲫⲑⲉⲧⲱ̀ⲗⲓ ⲙ̀ⲫ̀ⲛⲟⲃⲓ ⲛ̀ⲧⲉ ⲡⲓⲕⲟⲥⲙⲟⲥ ϣⲉⲡ ⲛⲉⲛϯϩⲟ ⲉ̀ⲣⲟⲕ. Ⲫⲑⲉⲧϩⲉⲙⲥⲓ ⲥⲁⲟⲩⲓ̀ⲛⲁⲙ ⲙ̀Ⲡⲉϥⲓⲱⲧ ⲛⲁⲓ ⲛⲁⲛ.", 
"Seigneur Dieu, Agneau de Dieu, le Fils du Père, Toi qui enlève le péché du monde, aie pitié de nous. Toi qui enlève le péché du monde, reçois notre prière. Toi qui es assis à la droite du Père, aie pitié de nous. Toi seul es Saint;", 
"", 
"أَيُّهَااَلرَبّ الإله، حمل اللّه، ابن الآب، رافع خطية العالم، ارْحَمْنَا. يا حامل خطية العالم، اقْبَلْ طلباتنا إليك. أيُّهَا الجالس عن يمين أبيه، ارْحَمْنَا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲛ̀ⲟ̀ⲕ ⲙ̀ⲙⲁⲩⲁⲧⲕ ⲉⲟ̀ⲩⲁⲃ: ⲛ̀ⲟ̀ⲕ ⲙ̀ⲙⲁⲩⲁⲧⲕ ⲉⲧϭⲟⲥⲓ: Ⲡⲁϭⲟⲓⲥ Ⲓⲑⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲟ̀ⲩⲁⲃ ⲉ̀ⲟⲩⲱ̀ⲟⲩ ⲙ̀Ⲫ̀ⲛⲟⲩϯ Ⲫ̀ⲓⲱⲧ ⲁ̀ⲙⲑⲛ.", 
"Toi seul es le Très-Haut, ô Seigneur, Jésus-Christ, avec le Saint-Esprit. Gloire à Dieu le Père. Amen.", 
"", 
"أنت وحدك القُدُّوسْ. أنْتَ وحدك العالي يا رَبّى يَسُوعْ المَسِيحْ والْرُوحْ القُدُسْ. مجدا لله الآب آمْينْ.", 
],
[
Prefix.same+"&C=Assembly", 
"Ϯⲛⲁⲥ̀ⲙⲟⲩ ⲉ̀ⲣⲟⲕ ⲙ̀ⲙⲑⲛⲓ ⲙ̀ⲙⲑⲛⲓ: ϯⲛⲁⲥ̀ⲙⲟⲩ ⲉ̀ⲡⲉⲕⲣⲁⲛ ⲉⲟ̀ⲩⲁⲃ ϣⲁ ⲉ̀ⲛⲉϩ ⲛⲉⲙ ϣⲁ ⲉ̀ⲛⲉϩ ⲛ̀ⲧⲉ ⲛⲓⲉ̀ⲛⲉϩ ⲁ̀ⲙⲑⲛ. Ⲓⲥϫⲉⲛ ϫⲱⲣϩ ⲁ̀ ⲡⲁⲡ̀ⲛⲉⲩⲙⲁ ϣⲱⲣⲡ ⲙ̀ⲙⲟϥ ϩⲁⲣⲟⲕ Ⲡⲁⲛⲟⲩϯ: ϫⲉ ϩⲁⲛⲟⲩⲟⲩⲱⲓⲛⲓ ⲛⲉ ⲛⲉⲕⲟⲩⲁϩⲥⲁϩⲛⲓ ϩⲓϫⲉⲛ ⲡⲓⲕⲁϩⲓ. Ⲛⲁⲓⲉⲣⲙⲉⲗⲉⲧⲁⲛ ϩⲓϫⲉⲛ ⲛⲉⲕⲙⲱⲓⲧ: ϫⲉ ⲁⲕϣⲱⲡⲓ ⲛⲑⲓ ⲛ̀ⲟⲩⲃⲟⲑⲟ̀ⲥ. Ϩⲁⲛⲁ̀ⲧⲟⲟⲩⲓ̀ Ⲡ̀ϭⲟⲓⲥ ⲉⲕⲉ̀ⲥⲱⲧⲉⲙ ⲉ̀ⲧ̀ⲥ̀ⲙⲑ: ϣⲱⲣⲡ ⲉⲓⲉ̀ⲧⲁϩⲟⲓ ⲛⲁϩⲣⲁⲕ ⲉⲕⲉ̀ⲛⲁⲩ ⲉ̀ⲣⲟⲓ.", 
"Je te bénirai tous les jours et je louerai Ton saint Nom chaque jour et à jamais. Amen! Dès la nuit, mon esprit se tourne vers Toi ô mon Dieu car tes commandements sont des lumières sur la terre. Je suivais Tes chemins car Tu es mon secours. Demain je me tiendrai devant Toi et tu me verras.", 
"", 
"أباركك كُلِّ يوم، وأسبح اسمك القُدُّوسْ إلى الأبد. وإلى أبد الأبد. آمْينْ. منذ الليل روحي تبكر إليَكَ يا إلهي، لِأنَّ أوامرك هي نور  على الأرْضَ. كُنْتُ أتلو في طرقك، لأنَّكَ صِرْتَ لي مَعَينا. باكرا يا رَبّ تسمع صوتي، بالغداة أقف أمامك وتراني.", 
],
],
[
[
Prefix.commonPrayer+"HolyGodHolyPowerfull&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"HolyGodHolyPowerfullPart1&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"GloryToTheFatherTheSonAndTheSpirit&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"NowAlwaysAndForEver&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"HolyGodHolyPowerfullPart2&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"HolyGodHolyPowerfullPart1&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Le Trisagion", 
"", 
" قُدُّوسْ اللّه", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲁⲅⲓⲟⲥ ⲟ̀ Ⲑⲉⲟⲥ: Ⲁⲅⲓⲟⲥ Ⲓⲥⲭⲩⲣⲟⲥ: Ⲁⲅⲓⲟⲥ Ⲁⲑⲁⲛⲁⲧⲟⲥ: ⲟ̀ ⲉⲕⲡⲁⲣⲑⲉⲛⲟⲩ ⲅⲉⲛⲛⲉⲑⲓⲥ: ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ ⲏ̀ⲙⲁⲥ.", 
"Dieu Saint, Saint fort, Saint immortel, né de la Vierge, aie pitié de nous.", 
"آجيوس أو ثيؤس، آجيوس يس شيروس، آجيوس آثاناتوس، أو إكبارثينو جيننيثيس، إلايسون ايماس.", 
"قُدُّوسْ اللّه، قُدُّوسْ القوى، قُدُّوسْ الحى الذي لا يموت، يا من ولد من العَذْراءْ ارْحَمْنَا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲁⲅⲓⲟⲥ ⲟ̀ Ⲑⲉⲟⲥ: Ⲁⲅⲓⲟⲥ Ⲓⲥⲭⲩⲣⲟⲥ: Ⲁⲅⲓⲟⲥ Ⲁⲑⲁⲛⲁⲧⲟⲥ: ⲟ̀ ⲥ̀ⲧⲁⲩⲣⲱⲑⲓⲥ ⲇⲏⲙⲁⲥ: ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ ⲏ̀ⲙⲁⲥ.", 
"Dieu Saint, Saint fort, Saint immortel, crucifié pour nous, aie pitié de nous.", 
"آجيوس أو ثيؤس، آجيوس يس شيروس، آجيوس أثاناتوس، أو إستافروثيس ذي إيماس، إلايسون ايماس.", 
"قُدُّوسْ اللّه، قُدُّوسْ القوى، قُدُّوسْ الحى الذي لا يموت، يا من صلب عنا. ارْحَمْنَا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲁⲅⲓⲟⲥ ⲟ̀ Ⲑⲉⲟⲥ: Ⲁⲅⲓⲟⲥ Ⲓⲥⲭⲩⲣⲟⲥ: Ⲁⲅⲓⲟⲥ Ⲁⲑⲁⲛⲁⲧⲟⲥ: ⲟ̀ ⲁ̀ⲛⲁⲥⲧⲁⲥ ⲉⲕⲧⲱⲛ ⲛⲉⲕⲣⲱⲛ: ⲕⲉ ⲁ̀ⲛⲉⲗⲑⲱⲛ ⲓⲥ ⲧⲟⲩⲥ ⲟⲩⲣⲁⲛⲟⲩⲥ: ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ ⲏ̀ⲙⲁⲥ.", 
"Dieu Saint, Saint fort, Saint immortel, ressuscité d’entre les morts et monté aux cieux, aie pitié de nous.", 
"آجيوس أو ثيؤس، آجيوس يس شيروس، آجيوس آثاناتوس، أو آناستاس إكتون نيكرون، كي آنيلثون يس توس أورانوس، إلايسون إيماس.", 
"قُدُّوسْ اللّه، قُدُّوسْ القَوي، قُدُّوسْ الحَىّ الذي لا يَمْوتْ، يا مَنْ قَامَ مِنَ الأَمْواتْ وصَعِدَ إلى السَّمَواتْ، ارْحَمْنَا.", 
],
],
[
[
Prefix.commonPrayer+"GloryToTheFatherTheSonAndTheSpirit&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲇⲟⲝⲁ ⲡⲁⲧⲣⲓ ⲕⲉ Ⲩ̀Ϯⲓⲱ ⲕⲉ ⲁⲅⲓⲱ Ⲡ̀ⲛⲉⲩⲙⲁⲧⲓ", 
"Gloire au Père, au Fils et au Saint Esprit.", 
"ذوكسا باتري كي إيو، كي آجيو ابنيفماتي.", 
"المجد للآب والابن والْرُوحْ القُدُسْ.", 
],
],
[
[
Prefix.commonPrayer+"NowAlwaysAndForEver&D=$copticFeasts.AnyDay&C=Assembly", 
"ⲕⲉ ⲛⲩⲛ ⲕⲉ ⲁ̀ⲓ̀ ⲕⲉ ⲓⲥ ⲧⲟⲩⲥ ⲉ̀ⲱ̀ⲛⲁⲥ ⲧⲱⲛ ⲉ̀ⲱ̀ⲛⲱⲛ: ⲁ̀ⲙⲏⲛ:", 
"Maintenant et toujours et dans les siècles des siècles. Amen.", 
"كي نين كي آي إي، كي استوس إي أوناستون إي أونون آمْينْ.", 
"الآن وكُلَّ أوانْ وإلى دَهْرِ الدُهُورْ آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"HolyGodHolyPowerfullPart2&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲁⲅⲓⲁ Ⲧ̀ⲣⲓⲁⲥ ̀ⲉ̀ⲗⲉⲑ̀ⲥⲟⲛ ⲑ̀ⲙⲁⲥ: ⲡⲁⲛⲁ̀ⲅⲓⲁ Ⲧ̀ⲣⲓⲁⲥ ̀ⲉ̀ⲗⲉⲑ̀ⲥⲟⲛ ⲑ̀ⲙⲁⲥ: Ϯⲧ̀ⲣⲓⲁⲥ ⲉⲟ̀ⲩⲁⲃ ⲛⲁⲓ ⲛⲁⲛ. Ⲡ̀ϭⲟⲓⲥ ⲭⲁ ⲛⲉⲛⲛⲟⲃⲓ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ: Ⲡ̀ϭⲟⲓⲥ ⲭⲁ ⲛⲉⲛⲁ̀ⲛⲟⲙⲓⲁ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ: Ⲡ̀ϭⲟⲓⲥ ⲭⲁ ⲛⲉⲛⲡⲁⲣⲁⲡⲧⲱⲙⲁ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ. Ⲡ̀ϭⲟⲓⲥ ϫⲉⲙⲡ̀ϣⲓⲛⲓ ⲛ̀ⲑⲉⲧϣⲱⲛⲓ ⲛ̀ⲧⲉ ⲡⲉⲕⲗⲁⲟⲥ: ⲙⲁⲧⲁϭⲱⲟⲩ ⲉⲃ̀ⲉ ⲡⲉⲕⲣⲁⲛ ⲉⲟ̀ⲩⲁⲃ.", 
"Ô Trinité sainte, aie pitié de nous. Ô Trinité Sainte, aie pitié de nous. Ô Trinité Sainte, aie pitié de nous. Seigneur, pardonne-nous nos péchés. Seigneur, pardonne-nous nos iniquités. Seigneur, pardonne-nous nos erreurs. Visite Seigneur les malades de Ton peuple; guéris-les à cause de Ton Saint Nom.", 
"", 
"أَيُّهَااَلثَالُوثْ القُدُّوسْ ارْحَمْنَا. أيُّهَا الثَالُوثْ القُدُّوسْ ارْحَمْنَا. أيُّهَا الثَالُوثْ القُدُّوسْ ارْحَمْنَا. يا رَبّ اغْفِرْ لَنَا خَطَايَانَا، يا رَبّ اغفر لنا آثامنا، يا رَبّ اغفر لنا زلاتنا. يا رَبّ افتقد مرضى شعبك، اشفهم من أجل اسمك القُدُّوسْ.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲛⲉⲛⲓⲟϯ ⲛⲉⲙ ⲛⲉⲛⲥ̀ⲛⲑⲟⲩ ⲉ̀ⲧⲁⲩⲉ̀ⲛⲕⲟⲧ Ⲡ̀ϭⲟⲓⲥ ⲙⲁⲙ̀ⲧⲟⲛ ⲛ̀ⲛⲟⲩⲯⲩⲭⲑ. Ⲡⲓⲁⲛ̀ⲟⲃⲓ Ⲡ̀ϭⲟⲓⲥ ⲛⲁⲓ ⲛⲁⲛ: ⲡⲓⲁⲛ̀ⲟⲃⲓ Ⲡ̀ϭⲟⲓⲥ ⲁ̀ⲣⲓⲃⲟⲑⲓ̀ⲛ ⲉ̀ⲣⲟⲛ: ϣⲉⲡ ⲛⲉⲛϯϩⲟ ⲉ̀ⲣⲟⲕ. Ϫⲉ ⲫⲱⲕ ⲡⲉ ⲡⲓⲱ̀ⲟⲩ ⲛⲉⲙ ⲡⲓⲁ̀ⲙⲁϩⲓ: ⲛⲉⲙ ⲡⲓⲧ̀ⲣⲓⲁⲥ ⲁ̀ⲅⲓⲟⲥ:", 
"A nos pères et à nos frères qui se sont endormis, accorde Seigneur le repos de leurs âmes. Ô Toi qui es sans péché, Seigneur aie pitié de nous. Ô Toi qui es sans péché, Seigneur aide nous et reçois nos supplications car à Toi sont dues la gloire, la magnificence et la sanctification trinitaire.", 
"", 
"آباؤنا وإخوتنا الذين رقدوا، يا رَبّ نيح نفوسهم. يا من هو بلا خطية، يا رَبّ ارْحَمْنَا. يا من بلا خطية، يا رَبّ أعنا، واقبل طلباتنا إليك. لِأنَّ لَكَ المَجْدُ والعزة والتقديس المثلث.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲕⲩⲣⲓⲉ ⲉ̀ⲗⲉⲑ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ ⲉ̀ⲗⲉⲑ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ ⲩ̀ⲗⲟⲅⲑⲥⲟⲛ ⲁ̀ⲙⲑⲛ.", 
"Pitié Seigneur, pitié Seigneur, Seigneur bénis-nous . Amen !", 
"كيريالَيسون، كيريالَيسون، كيريالَيسون. آمْينْ.", 
"يا رَبّ ارحم. يا رَبّ ارحم يا رَبّ بارك. آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"WeSaluteYouMary&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Nous Te saluons et nous te supplions", 
"", 
" السَّلامُ لكي", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲭⲉⲣⲉ ⲛⲉ ⲧⲉⲛϯϩⲟ ⲉ̀ⲣⲟ: ⲱ̀ ⲑⲏⲉⲑⲟⲩⲁⲃ ⲉⲑⲙⲉϩ ⲛ̀ⲱ̀ⲟⲩ: ⲉⲧⲟⲓ ⲙ̀ⲡⲁⲣⲑⲉⲛⲟⲥ ⲛ̀ⲥⲏⲟⲩ ⲛⲓⲃⲉⲛ: ϯⲙⲁⲥⲛⲟⲩϯ ⲑ̀ⲙⲁⲩ ⲙ̀Ⲡⲭ̅ⲥ. Ⲁⲛⲓⲟⲩⲓ ⲛ̀ⲧⲉⲛⲡ̀ⲣⲟⲥⲉⲩⲭⲏ: ⲉ̀ⲡ̀ϣⲱⲓ ϩⲁ ⲡⲉϣⲏⲣⲓ ⲙ̀ⲙⲉⲛⲣⲓⲧ: ⲛ̀ⲧⲉϥⲭⲁ ⲛⲉⲛⲛⲟⲃⲓ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ.", 
"Nous Te saluons et nous te supplions, toi la sainte, pleine de gloire, toujours vierge, Mère de Dieu et mère du Christ: Fais monter nos prières vers ton Fils bien-aimé pour qu’Il nous pardonne nos péchés", 
"شيري ني تين تيهو إيرو أو ثي اثؤواب إيميه إن أووه. إتؤي إمبارثينوس إنسيو نيفين. تي ماسنؤتي إثُمَّاف إمبي اخرستوس. آني أوي إنتيني إبروس افشي. إي إبشوي خا بيشيري إممينريت. إنتي إفشي إننوفي نان إيفول.", 
"السَّلامُ لك. نسألك أيتها القِدِّيسَةْ الممتلئة مجداً العَذْراءْ كُلِّ حين، والدة الإله، أم المسيح، اصعدي صلواتنا إلى ابنك الحبيب ليغفر لنا خَطَايَانَا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲭⲉⲣⲉ ⲑⲏⲉ̀ⲧⲁⲥⲙⲓⲥⲓ ⲛⲁⲛ: ⲙ̀ⲡⲓⲟⲩⲱⲓⲛⲓ ⲛ̀ⲧⲁⲫ̀ⲙⲏⲓ: Ⲡⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ: ϯⲡⲁⲣⲑⲉⲛⲟⲥ ⲉⲑⲟⲩⲁⲃ. Ⲙⲁϯϩⲟ ⲙ̀Ⲡ̀ϭⲟⲓⲥ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ϫⲱⲛ: ⲛ̀ⲧⲉϥⲉⲣⲟⲩⲛⲁⲓ ⲛⲉⲙ ⲛⲉⲛⲯⲩⲭⲏ: ⲛ̀ⲧⲉϥⲭⲁ ⲛⲉⲛⲛⲟⲃⲓ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ", 
"Nous saluons la sainte Vierge qui à enfanté pour nous la lumière véritable, le Christ, notre Dieu, supplie le Seigneur pour nous afin qu’il accorde Sa miséricorde à nos âmes et nous pardonne nos péchés .", 
"شيري ثي إتاس ميسي نان، إمبي أو أويني إنتاف إمي بيخرستوس بينوتي، تي بارثينوس ماثؤواب. ماتي هو إم ابتشويس إي إهري إجون. إنتيف إر أوناي نيم نين فوشي. إنتيف كان اوفي نان إيفول.", 
"السَّلامُ للتي ولدت لنا النور الحقيقي المَسِيحْ إلهنا، العَذْراءْ القِدِّيسَةْ،اسألي الرَبّ عنا، ليصنع رحمة مَعَ نفوسنا ، ويغفر لنا خَطَايَانَا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ϯⲡⲁⲣⲑⲉⲛⲟⲥ Ⲙⲁⲣⲓⲁⲙ: ϯⲑⲉⲟ̀ⲧⲟⲕⲟⲥ ⲉⲑⲟⲩⲁⲃ: ϯⲡ̀ⲣⲟⲥⲧⲁⲧⲏⲥ ⲉ̀ⲧⲉⲛϩⲟⲧ: ⲛ̀ⲧⲉ ⲡ̀ⲅⲉⲛⲟⲥ ⲛ̀ⲧⲉ ϯⲙⲉⲧⲣⲱⲙⲓ. Ⲁⲣⲓⲡ̀ⲣⲉⲥⲃⲉⲩⲓⲛ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ϫⲱⲛ: ⲛⲁϩⲣⲉⲛ Ⲡⲭ̅ⲥ̅ ⲫⲏⲉ̀ⲧⲁⲣⲉϫ̀ⲫⲟϥ: ϩⲟⲡⲱⲥ ⲛ̀ⲧⲉϥⲉⲣϩ̀ⲙⲟⲧ ⲛⲁⲛ: ⲙ̀ⲡⲓⲭⲱ ⲉ̀ⲃⲟⲗ ⲛ̀ⲧⲉ ⲛⲉⲛⲛⲟⲃⲓ. Intercède pour nous devant le Christ que tu as enfanté afin qu’Il nous accorde la rémission de nos péchés .", 
"O Vierge Marie, Mère de Dieu, sainte et médiatrice, fidèle au genre humain", 
"تي بارثينوس ماريام، تي ثيؤطوكوس إثؤواب تي إبروستا تيس إتينهوت. إنتي إبجينوس إنتي تي ميترومي. آري إبريسفيفين إي إهري إيجون ناهرين ابشويس في إتار إيجفوف هوبوس إنتيف إر إهموت نان إمبيكو إيفول إنتي نينوفي.", 
"أيتها العَذْراءْ مَرِيَمْ والدة الإله القِدِّيسَةْ الشفيعة الأمينة لجنس البشرية،اشفعي فينا أمام المَسِيحْ الذي ولدته لكي ينعم عَلَيْنَا بغفران خَطَايَانَا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲭⲉⲣⲉ ⲛⲉ ⲱ̀ ϯⲡⲁⲣⲑⲉⲛⲟⲥ: ϯⲟⲩⲣⲱ ⲙ̀ⲙⲏⲓ ⲛ̀ⲁ̀ⲗⲏⲑⲓⲛⲏ: ⲭⲉⲣⲉ ⲡ̀ϣⲟⲩϣⲟⲩ ⲛ̀ⲧⲉ ⲡⲉⲛⲅⲉⲛⲟⲥ: ⲁ̀ⲣⲉϫ̀ⲫⲟ ⲛⲁⲛ ⲛ̀Ⲉⲙⲙⲁⲛⲟⲩⲏⲗ", 
"Ô Vierge, salut à toi Toi la reine véritable Salut, fierté du genre humain Tu enfantas Emmanuel.", 
"شيري ني أو تي بارثينوس، تي أورو إممي إن آن إليثينوس، شيري إبشوشو إنتي بينجينوس آري إجفو نان إن إممانويل.", 
"السَّلامُ لَكَ أيتها العَذْراءْ الملكة الحقيقية، السَّلامُ لفخر جنسنا، ولدت لنا عمانوئيل.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲧⲉⲛϯϩⲟ ⲁ̀ⲣⲉⲡⲉⲛⲙⲉⲩⲓ̀: ⲱ̀ ϯⲡ̀ⲣⲟⲥⲧⲁⲧⲏⲥ ⲉ̀ⲧⲉⲛϩⲟⲧ: ⲛⲁϩⲣⲉⲛ ⲡⲉⲛⲟ̅ⲥ̅ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅: ⲛ̀ⲧⲉϥⲭⲁ ⲛⲉⲛⲛⲟⲃⲓ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ.", 
"Souviens-toi, nous t’implorons Ô intercesseur fidèle devant notre Seigneur Jésus-Christ Pour qu’Il nous pardonne nos péchés.", 
"تي تيهو آري بين ميفئي إو تي إبروس تاتيس إي إتينهوت ناهرين بينشويس إيسوس باخرستوس، إنتيف كا نيننوفي نان إيفول.", 
"نسألك أنْ تذكرينا أيتها الشفيعة المؤتمنة أمام رَبّنا يَسُوعْ المَسِيحْ ليغفر لنا خَطَايَانَا.", 
],
],
[
[
Prefix.commonPrayer+"WeExaltYouStMary&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Nous t’exaltons ô Mère de la vraie Lumière", 
"", 
" نعظمك يا أم النور الحقيقي", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲧⲉⲛϭⲓⲥⲓ ⲙ̀ⲙⲟ ⲑ̀ⲙⲁⲩ ⲙ̀ⲡⲓⲟⲩⲱⲓⲛⲓ ⲛ̀ⲧⲁ ⲫ̀ⲙⲏⲓ: ⲧⲉⲛϯⲱ̀ⲟⲩ ⲛⲉ ⲱ̀ ⲑⲏⲉ̀ⲑⲟⲩⲁⲃ ⲟⲩⲟϩ ⲙ̀ⲙⲁⲥⲛⲟⲩϯ: ϫⲉ ⲁⲣⲉⲙⲓⲥⲓ ⲛⲁⲛ ⲙ̀ⲡ̀ⲥⲱⲧⲏⲣ ⲙ̀ⲡⲓⲕⲟⲥⲙⲟⲥ ⲧⲏⲣϥ: ⲁϥⲓ̀ ⲟⲩⲟϩ ⲁϥⲥⲱϯ ⲛ̀ⲛⲉⲛⲯⲩⲭⲏ.", 
"Nous t’exaltons ô Mère de la vraie Lumière, et nous te glorifions ô sainte Mère de Dieu, car tu as enfanté pour nous le Sauveur du monde.", 
"", 
"نعظمك يا أم النور الحقيقي، ونمجدك أيتها العَذْراءْ القِدِّيسَةْ، والدة الإله، لأنَّكَ ولدت لنا مخلص العالم، أتى وخلص نفوسنا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲟⲩⲱ̀ⲟⲩ ⲛⲁⲕ ⲡⲉⲛⲛⲏⲃ ⲡⲉⲛⲟⲩⲣⲟ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ: ⲡ̀ϣⲟⲩϣⲟⲩ ⲛ̀ⲛⲓⲁ̀ⲡⲟⲥⲧⲟⲗⲟⲥ: ⲡⲓⲭ̀ⲗⲟⲙ ⲛ̀ⲧⲉ ⲛⲓⲙⲁⲣⲧⲩⲣⲟⲥ: ⲡ̀ⲑⲉⲗⲏⲗ ⲛ̀ⲛⲓⲇⲓⲕⲉⲟⲥ: ⲡ̀ⲧⲁϫⲣⲟ ⲛ̀ⲛⲓⲉⲕⲕ̀ⲗⲏⲥⲓⲁ̀: ⲡ̀ⲭⲱ ⲉ̀ⲃⲟⲗ ⲛ̀ⲧⲉ ⲛⲓⲛⲟⲃⲓ.", 
"Il est venu et a sauvé nos âmes. Gloire à Toi ô notre Seigneur et notre Roi, le Christ: fierté des apôtres, couronne des martyrs, allégresse des justes, affermissement des Églises et rémission des péchés.", 
"", 
"المجد لكَ يا سَيِّدنْا وملكنا المسيح، فخر الرسل، إكليل الشهداء تهليل الصديقين، ثبات الكنائس، غفران الخطايا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲧⲉⲛϩⲓⲱⲓϣ ⲛ̀ϯⲧ̀ⲣⲓⲁⲥ ⲉ̀ⲑⲟⲩⲁⲃ: ⲉⲥ ϧⲉⲛ ⲟⲩⲙⲉⲑⲛⲟⲩϯ ⲛ̀ⲟⲩⲱⲧ: ⲧⲉⲛⲟⲩⲱϣⲧ ⲙ̀ⲙⲟⲥ ⲧⲉⲛϯⲱⲟⲩ ⲛⲁⲥ: Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ̀ ⲉⲩⲗⲟⲅⲏⲥⲟⲛ: ⲁ̀ⲙⲏⲛ.", 
"Nous proclamons la Trinité sainte: Une seule Divinité; nous l’adorons et nous la glorifions. Pitié Seigneur, Pitié Seigneur, Seigneur bénis-nous. Amen !", 
"", 
"نبشر بالثَالُوثْ القُدُّوسْ، لاهوت واحد، نسجد لَهُ ونمجده. يا رَبّ ارحم. يا رَبّ ارحم. يا رَبّ بارك. آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"Creed&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Credo", 
"", 
" قانون الإيمان", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲧⲉⲛⲛⲁϩϯ ⲉ̀ⲟ̀ⲩⲚⲟⲩϯ ⲛ̀ⲟ̀ⲩⲱ̀ⲧ: Ⲫϯ Ⲫ̀ⲓⲱⲧ ⲡⲓⲠⲁⲛⲧⲟⲕⲣⲁⲧⲱⲣ: ⲫⲏⲉ̀ⲧⲁϥⲑⲁⲙⲓⲟ ⲛ̀ⲧ̀ⲫⲉ ⲛⲉⲙ ⲡ̀ⲕⲁϩⲓ: ⲛⲏⲉ̀ⲧⲟⲩⲛⲁⲩ ⲉ̀ⲣⲱⲟ̀ⲩ ⲛⲉⲙ ⲛⲏⲉ̀ⲧⲉ ⲛ̀ⲥⲉⲛⲁⲩ ⲉ̀ⲣⲱⲟ̀ⲩ ⲁⲛ.", 
"En vérité je crois en Un seul Dieu, le Père Tout Puissant Créateur du ciel et de la terre, de toutes les choses visibles et invisibles.", 
"", 
"بالحقيقة نؤمن بإله واحد، اللّه الآب ضَابِطْ الكُلّ، خالق السَّمَاء والأرض، ما يُرَى وما لا يُرَى.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲧⲉⲛⲛⲁϩϯ ⲉ̀ⲟⲩⲟ̅ⲥ̅ ⲛ̀ⲟⲩⲱⲧ Ⲓⲏ/ⲥ/ Ⲡⲭ/ⲥ/ ϮⲠϣⲏⲣⲓ ⲙ̀Ⲫϯ ⲡⲓⲙⲟⲛⲟⲅⲉⲛⲏⲥ: ⲡⲓⲙⲓⲥⲓ ⲉ̀ⲃⲟⲗϧⲉⲛ ϮⲪⲓⲱⲧ ϧⲁϫⲱⲟⲩ ⲛ̀ⲛⲓⲉ̀ⲱⲛ ⲧⲏⲣⲟⲩ: ⲟⲩⲟⲩⲱⲓⲛⲓ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲟⲩⲟⲩⲱⲛⲓ: ⲟⲩⲛⲟⲩϯ ⲛ̀ⲧⲁⲫ̀ⲙⲏⲓ", 
"Je crois en Un seul Seigneur Jésus Christ le Fils unique de Dieu né du Père avant tous les siècles. Lumière née de la Lumière.", 
"", 
"نؤمن برَبٍّ واحد، يَسُوعْ المسيح، ابنُ اللّه الوَحِيد، المولود من الآب قبل كُلِّ الدهور. نور من نور، إله حق من إله حق.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲟ̀ⲩⲙⲓⲥⲓ ⲡⲉ ⲟ̀ⲩⲑⲁⲙⲓⲟ ⲁⲛ ⲡⲉ: ⲟ̀ⲩⲟ̀ⲙⲟⲟⲩⲥⲓⲟⲥ ⲡⲉ ⲛⲉⲙ Ⲫ̀ⲓⲱⲧ: ⲫⲏⲉ̀ⲧⲁ ϩⲱⲃ ⲛⲓⲃⲉⲛ ϣⲱⲡⲓ ⲉ̀ⲃⲟⲗ ϩⲓⲧⲟⲧϥ. Ⲫⲁⲓ ⲉ̀ⲧⲉ ⲉⲑⲃⲏⲧⲉⲛ ⲁ̀ⲛⲟⲛ ϧⲁ ⲛⲓⲣⲱⲙⲓ ⲛⲉⲙ ⲉⲑⲃⲉ ⲡⲉⲛⲟ̀ⲩϫⲁⲓ: ⲁϥⲓ̀ ⲉ̀ⲡⲉⲥⲏⲧ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲧ̀ⲫⲉ: ⲁϥϭⲓⲥⲁⲣⲝ ⲉ̀ⲃⲟⲗ ϧⲉⲛ ⲡⲓⲠ̀ⲛⲉⲩⲙⲁ ⲉ̅ⲑ̅ⲩ̅ ⲛⲉⲙ ⲉ̀ⲃⲟⲗϧⲉⲛ Ⲙⲁⲣⲓⲁ ϯⲠⲁⲣⲑⲉⲛⲟⲥ ⲟⲩⲟϩ ⲁϥⲉ̀ⲣⲣⲱⲙⲓ.", 
"Vrai Dieu né du Vrai Dieu, engendré, non pas créé, consubstantiel au Père, Par qui tout a été fait, qui pour nous, les hommes, et pour notre salut, est descendu du ciel. Par l’Esprit Saint il a pris chair de la Vierge Marie et s’est fait homme .", 
"", 
"مولود غَيْرُ مخلوق، مساوى للآب في الجوهر، الذي به كان كُلِّ شىء. هَذا الذي من أجلنا نحنُ البشر، ومن أجل خلاصنا، نَزَلَ من السَّمَاء، وتجسدَ من الْرُوحْ القُدُسْ ومن مَرِيَمْ العذراء. وتأنس.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲟⲩⲟϩ ⲁⲩⲉ̀ⲣⲥ̀ⲧⲁⲩⲣⲱⲛⲓⲛ ⲙ̀ⲙⲟϥ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ϫⲱⲛ ⲛⲁϩⲣⲉⲛ Ⲡⲟⲛⲧⲓⲟⲥ Ⲡⲓⲗⲁⲧⲟⲥ: ⲁϥϣⲉⲡⲉ̀ⲙⲕⲁϩ ⲟⲩⲟϩ ⲁⲩⲕⲟⲥϥ. Ⲟⲩⲟϩ ⲁϥⲧⲱⲛϥ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲏⲉ̀ⲑⲙⲱⲟ̀ⲩⲧ ϧⲉⲛ ⲡⲓⲉ̀ϩⲟⲟ̀ⲩ ⲙ̀ⲙⲁϩϣⲟⲙⲧ ⲕⲁⲧⲁ ⲛⲓⲅ̀ⲣⲁⲫⲏ.", 
"Il a été crucifié pour nous sous Ponce Pilate, a souffert et a été enseveli. Il est ressuscité le troisième jour conformément aux écritures.", 
"", 
"وصُلِبَ عنا على عهد بيلاطس البنطي. تألمَ وقبرَ وقامَ من الأموات في اليوم الثالث، كما في الكتب.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ̀: ⲁϥϩⲉⲙⲥⲓ ⲥⲁⲟⲩⲓ̀ⲛⲁⲙ ⲙ̀Ⲡⲉϥⲓⲱⲧ. Ⲕⲉ ⲡⲁⲗⲓⲛ ϥ̀ⲛⲏⲟⲩ ϧⲉⲛ ⲡⲉϥⲱ̀ⲟ̀ⲩ ⲉ̀ϯϩⲁⲡ ⲉ̀ⲛⲏⲉ̀ⲧⲟⲛϧ ⲛⲉⲙ ⲛⲏⲉ̀ⲑⲙⲱⲟ̀ⲩⲧ: ⲫⲏⲉ̀ⲧⲉ ⲧⲉϥⲙⲉⲧⲟⲩⲣⲟ ⲟ̀ⲩⲁ̀ⲑⲙⲟⲩⲛⲕ ⲧⲉ.", 
"Il est monté au ciel et s’est assis à la droite du Père d’où Il reviendra dans Sa gloire pour juger les vivants et les morts et son règne n’aura pas de fin.", 
"", 
"وصَعِدَ إلى السَّمَواتْ، وجَلسَ عن يمين أبيه. وأيضاً يأتي في مجدهِ ليَدينَ الأحياءَ والأموات، الذي لَيْسَ لملكِهِ انقضاء.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲥⲉ ⲧⲉⲛⲛⲁϩϯ ⲉ̀ⲡⲓⲠ̀ⲛⲉⲩⲙⲁ ⲉ̅ⲑ̅ⲩ̅ Ⲡⲟ̅ⲥ̅ ⲛ̀ⲣⲉϥϯ ⲙ̀ⲡ̀ⲱ̀ⲛϧ: ⲫⲏⲉ̀ⲑⲛⲏⲟⲩ ⲉ̀ⲃⲟⲗϧⲉⲛ Ⲫ̀ⲓⲱⲧ: ⲥⲉⲟ̀ⲩⲱ̀ϣⲧ ⲙ̀ⲙⲟϥ ⲥⲉϯⲱ̀ⲟ̀ⲩ ⲛⲁϥ ⲛⲉⲙ Ⲫ̀ⲓⲱⲧ ⲛⲉⲙ ⲡ̀Ϣⲏⲣⲓ. Ⲫⲏⲉ̀ⲧⲁϥⲥⲁϫⲓ ϧⲉⲛ ⲛⲓⲡ̀ⲣⲟⲫⲏⲧⲏⲥ. Ⲉⲟ̀ⲩⲓ̀ ⲛ̀ⲁ̀ⲅⲓⲁ ⲛ̀ⲕⲁⲑⲟⲗⲓⲕⲏ ⲛ̀ⲁ̀ⲡⲟⲥⲧⲟⲗⲓⲕⲏ ⲛ̀ⲉ̀ⲕⲕⲗⲏⲥⲓⲁ. Ⲧⲉⲛⲉ̀ⲣⲟ̀ⲙⲟⲗⲟⲅⲓⲛ ⲛ̀ⲟ̀ⲩⲱ̀ⲙⲥ ⲛ̀ⲟ̀ⲩⲱ̀ⲧ ⲉ̀ⲡ̀،ⲱ ⲉ̀ⲃⲟⲗ ⲛ̀ⲧⲉ ⲛⲓⲛⲟⲃⲓ.", 
"Je crois en l’Esprit Saint qui est Seigneur et qui donne la vie; il procède du Père. Avec le Père et le Fils, Il reçoit même adoration et même gloire. Il a parlé par les prophètes. Je crois en l’Église, Une, Sainte, Universelle et Apostolique. Je reconnais un seul baptême pour le pardon des péchés.", 
"", 
"نعم نؤمن بالْرُوحْ القُدُسْ، الرَبّ المحيى المنبثق من الآب نسجدُ لهُ ونمجّدَهُ مَعَ الآب والابن، الناطق في الأنبياء. وبكنيسة واحدة مُقدسة جامعة رسولية. ونعترف بمعمودية واحدة لِمَغْفِرَةْ الخطايا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲧⲉⲛϫⲟⲩϣⲧ ⲉ̀ⲃⲟⲗ ϧⲁⲧ̀ϩⲏ ⲛ̀ϯⲁ̀ⲛⲁⲥⲧⲁⲥⲓⲥ ⲛ̀ⲧⲉ ⲛⲓⲣⲉϥⲙⲱⲟⲩⲧ: ⲛⲉⲙ ⲡⲓⲱⲛϧ ⲛ̀ⲧⲉ ⲡⲓⲉ̀ⲱⲛ ⲉⲑⲛⲏⲟⲩ: Ⲁⲙⲏⲛ.", 
"J’attends la résurrection des morts et la vie du monde à venir. Amen.", 
"تين جوشت إيفول خا إتهي إنتي آناستاسيس إنتي ني ريفموؤت، نيم بيؤنخ إنتي بي إيون اثنيو آمْينْ.", 
"وننتظر قيامَةَ الأموات وحياة الدهر الآتي آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲁⲙⲏⲛ.", 
"Amen.", 
"آمين", 
"آمين.", 
],
],
[
[
Prefix.commonPrayer+"EfnotiNaynan&D=$copticFeasts.AnyDay&C=Comments", 
"", 
"يرفع الكاهن الصَلِيبْ وعليه ثلاث شمعات موقدة ووجهه إلى الشَرْقِ ويقول:", 
],
[
Prefix.same+"&C=Priest", 
"Ⲫⲛⲟⲩϯⲛⲁⲓ ⲛⲁⲛ: Ⲑⲉϣⲟⲩⲛⲁⲓ ⲉ̀ⲣⲟⲛ: Ϣⲉⲛϩⲏⲧ ϧⲁⲣⲟⲛ.", 
"Dieu aie pitié. Accorde-nous ta miséricorde. Sois compatissant envers nous.", 
"افنوتي ناي نان، ثيشو ناي إيرونن شين هيت خارون", 
"اَللَّهُمَّ ارْحَمْنَا، قرر لنا رحمة، ترآف علينا.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
],
[
Prefix.same+"&C=Priest", 
"Ⲥⲱⲧⲉⲙ ⲉ̀ⲣⲟⲛ.", 
"Écoute- nous.", 
"سوتيم إيرون", 
"واسمعنا.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
],
[
Prefix.same+"&C=Priest", 
"Ⲥⲙⲟⲩ ⲉ̀ⲣⲟⲛ: ⲁ̀ⲣⲉϩ ⲉ̀ⲣⲟⲛ: ⲁ̀ⲣⲓⲃⲟⲏ̀ⲑⲓⲛ ⲉ̀ⲣⲟⲛ.", 
"Bénis-nous, préserve-nous, aide-nous.", 
"سمو إيرون، آريه إيرون آري فو إيثين إيرون", 
"باركنا واحفظنا وأعنا.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"Amen&D=$copticFeasts.AnyDay", 
],
[
Prefix.same+"&C=Priest", 
"Ⲱⲗⲓ ⲙ̀ⲡⲉⲕϫⲱⲛⲧ ⲉ̀ⲃⲟⲗ ϩⲁⲣⲟⲛ: ϫⲉⲙⲡⲉⲛϣⲓⲛⲓ ϧⲉⲛ ⲡⲉⲕⲟⲩϫⲁⲓ: ⲟⲩⲟϩ ⲭⲁ ⲛⲉⲛⲛⲟⲃⲓ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ.", 
"Eloigne de nous ta colère. Accorde-nous ton salut. Et pardonne-nous nos péchés.", 
"أولي إمبيك كونتي إيفوك هارون، جيم بين شيني خين بيك أوجاي، أووه كا إنين نوفي نان إيفول.", 
"وارفع غضبك عنا وافتقدنا بخلاصك واغْفِرْ لَنَا خَطَايَانَا.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"KyrieEliesonThreeTimes&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"KyrieEliesonThreeTimes&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲁ̀ⲙⲏⲛ Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ. Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ. Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ.", 
"Amen, Pitié Seigneur, Pitié Seigneur, Pitié Seigneur.", 
"آمين كيريالَيسون كيريالَيسون كيريالَيسون", 
"آمين يا رَبّ ارحم، يا رَبّ ارحم، يا رَبّ ارحم.", 
],
],
[
[
Prefix.commonPrayer+"GospelPrayerPlaceHolder&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"GospelPrayer&D=$copticFeasts.AnyDay&C=Comments", 
"", 
"يقدم الشماس للكاهن درج البخور فيضع يَدِ بَخُورفي المجمرة ويقول:.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"BlockShlilIriniPassi&D=$copticFeasts.AnyDay", 
],
[
Prefix.same+"&C=Title", 
"", 
"Oraison de l’Evangile", 
"", 
" أوشية الإنجيل", 
],
[
Prefix.same+"&C=Priest", 
"Ⲫⲛⲏⲃ ⲡ̀ϭⲟⲓⲥ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ ⲫⲏⲉ̀ⲧⲁϥϫⲟⲥ ⲛ̀ⲛⲉϥⲁ̀ⲅⲓⲟⲥ ⲉⲧⲧⲁⲓⲏⲟⲩⲧ ⲙ̀ⲙⲁⲑⲏⲧⲏⲥ ⲟⲩⲟϩ ⲛ̀ⲁⲡⲟⲥⲧⲟⲗⲟⲥ ⲉⲑⲟⲩⲁⲃ Ϫⲉ ϩⲁⲛⲙⲏϣ ⲙ̀ⲡ̀ⲣⲟⲫⲏⲧⲏⲥ ⲛⲉⲙ ϩⲁⲛⲑ̀ⲙⲏⲓ ⲁⲩⲉⲣ ⲉ̀ⲡⲓⲑⲩⲙⲓⲛ ⲉ̀ⲛⲁⲩ ⲉ̀ⲛⲏ ⲉ̀ⲧⲉⲧⲉⲛⲛⲁⲩ ⲉ̀ⲣⲱⲟⲩ ⲟⲩⲟϩ ⲙ̀ⲡⲟⲩⲛⲁⲩ: ⲟⲩⲟϩ ⲉ̀ⲥⲱⲧⲉⲙ ⲉ̀ⲛⲏ ⲉ̀ⲧⲉⲧⲉⲛⲥⲱⲧⲉⲙ ⲉ̀ⲣⲱⲟⲩ ⲟⲩⲟϩ ⲙ̀ⲡⲟⲩⲥⲱⲧⲉⲙ.", 
"Ô Maître, Seigneur Jésus Christ, notre Dieu, qui s’est adressé à Ses saints apôtres et bienheureux disciples en disant: “Que de nombreux prophètes et justes ont désiré voir ce que vous voyez et ne l’ont pas vu, et entendre ce que vous entendez, et ne l’ont pas entendu.", 
"فنيف إبتشويس ايسوس باخريستوس بننوتي في إيتافجوس إننيف آجيوس إتطايوت، إمماثيتيس، أووه إن أبوستولوس إثؤواب جي هانميش إم إبروفيتيس نيم هان إثُمَّي آفير إبي ثومين إناف إني إت إيتيناف أووه إمبوناف أووه إسؤ تيم إني إت إتينسوتيم، إرو أووه إمبو سوتيم.", 
"أَيُّهَااَلسيد الرَبّ يَسُوعْ المَسِيحْ الهنا الذي قال لتلاميذه القِدِّيسِينْ المكرمين ورسله الأطهار ان أنبياء وأبرار كثيرين اشتهوا أنْ يروا ما أنتم ترون ولم يروا وأن يسمعوا ما أنتم تسمعون ولم يسمعوا.", 
],
[
Prefix.same+"&C=Priest", 
"ⲛ̀ⲑⲱⲧⲉⲛ ⲇⲉ ⲱ̀ⲟⲩⲛⲓⲁⲧⲟⲩ ⲛ̀ⲛⲉⲧⲉⲛⲃⲁⲗ ϫⲉ ⲥⲉⲛⲁⲩ: ⲛⲉⲙ ⲛⲉⲧⲉⲛⲙⲁϣϫ ϫⲉ ⲥⲉⲥⲱⲧⲉⲙ: ⲙⲁⲣⲉⲛ ⲉⲣⲡ̀ⲉⲙⲡ̀ϣⲁ ⲛ̀ⲥⲱⲧⲉⲙ ⲟⲩⲟϩ ⲉ̀ⲓ̀ⲣⲓ ⲛ̀ⲛⲉⲕ ⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲉⲑⲟⲩⲁⲃ ϧⲉⲛ ⲛⲓⲧⲱⲃϩ ⲛ̀ⲧⲉ ⲛⲏⲉⲑⲟⲩⲁⲃ ⲛ̀ⲧⲁⲕ.", 
"Quant à vous, heureux sont vos yeux parce qu’ils voient et heureuses sont vos oreilles parce qu’elles entendent.” Rends nous dignes d’écouter et de pratiquer Tes saints évangiles par les prières de Tes saints.", 
"إن ثوتين جي أوأو نياتوف إنني تينفال جي سيناف، نيم انتين ماشج جي سي سوتيم ميارين ار إبيم إبشا إنسوتيم أووه إي إيري إننيك إف أنجيليون اثؤواب خين نيتوفه إنتي ني إثؤواب إنتاك.", 
"أما أنتم فطوبى لأعينكم لِأنَّهُا تبصر ولاذانكم لِأنَّهُا تسمع. فلنستحق أنْ نسمع ونعمل بأناجيلك المُقَدَّسْة بطلبات قديسيك.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲡⲣⲟⲥⲉⲩⲝⲁⲥⲑⲉ ⲩⲡⲡⲉⲣ ⲧⲟⲩ ⲁⲅⲓⲟⲩ ⲉⲩⲁⲅⲅⲉⲗⲓⲟⲩ.", 
"Priez pour le saint Évangile.", 
"بروس افكساثتي اوبير تو آجيو إن أنجيليو", 
"صلوا من أجل الإنجيل المُقَدَّسْ.", 
],
[
Prefix.same+"&C=Priest", 
"Ⲁⲣⲓⲫ̀ⲙⲉⲩⲓ ⲇⲉ ⲟⲛ ⲡⲉⲛⲛⲏⲃ ⲛ̀ⲟⲩⲟⲛ ⲛⲓⲃⲉⲛ ⲉⲧⲁⲩϩⲟⲛϩⲉⲛ ⲛⲁⲛ ⲉ̀ⲉⲣⲡⲟⲩⲙⲉⲩⲓ̀ ϧⲉⲛ ⲛⲉⲛϯϩⲟ ⲛⲉⲙ ⲛⲉⲛⲧⲱⲃϩ ⲉ̀ⲧⲉⲛⲓ̀ⲣⲓ ⲙ̀ⲙⲱⲟⲩ ⲉ̀ⲡ̀ϣⲱⲓ ϩⲁⲣⲟⲕ ⲡ̀ϭⲟⲓⲥ ⲡⲉⲛⲛⲟⲩϯ", 
"Souviens-Toi Seigneur, de tous ceux qui nous ont demandé de se souvenir d’eux dans nos supplications et nos prières que nous T’adressons, Seigneur Dieu", 
"", 
"اذكر ايضا ياسيدنا كُلِّ الذين أوصونا أنْ نذكرهم في تضرعاتنا وطلباتنا التي نرفعها اليك ايها الرَبّ الهنا", 
],
[
Prefix.same+"&C=Priest", 
"Ⲛⲏ ⲉⲧⲁⲩⲉⲣϣⲟⲣⲡ ⲛ̀ⲉⲛⲕⲟⲧ ⲙⲁⲙ̀ⲧⲟⲛ ⲛⲱⲟⲩ: ⲛⲏⲉⲧϣⲱⲛⲓ ⲙⲁⲧⲁⲗϭⲱⲟⲩ. Ϫⲉ ⲛ̀ⲑⲟⲕ ⲅⲁⲣ ⲡⲉ ⲡⲉⲛⲱⲛϧ ⲧⲏⲣⲟⲩ: ⲛⲉⲙ ⲡⲉⲛⲟⲩϫⲁⲓ ⲧⲏⲣⲟⲩ: ⲛⲉⲙ ⲧⲉⲛϩⲉⲗⲡⲓⲥ ⲧⲏⲣⲟⲩ: ⲛⲉⲙ ⲡⲉⲛⲧⲁⲗϭⲟ ⲧⲏⲣⲟⲩ: ⲛⲉⲙ ⲧⲉⲛⲁ̀ⲛⲁⲥⲧⲁⲥⲓⲥ ⲧⲏⲣⲉⲛ.", 
"Donne le repos aux âmes de ceux qui nous ont précèdes dans la mort et guéris les malades. Car Tu es notre vie, notre salut, notre espérance, notre guérison et notre résurrection à tous.", 
"", 
"الذين سبقوا فرقدوا نيحهم المرضي اشفهم لأنََكَ أنْتَ هو حياتنا كلنا وخلاصنا كلنا ورجاؤنا كلنا وشفاؤنا كلنا وقيامتنا كلنا .", 
],
[
Prefix.same+"&C=Comments", 
"", 
"ويكمل سرا:ـ.", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"", 
"", 
"وأنت الذي نرسل لَكَ إلى فوق المَجْدُ والكَرَامَةْ والسجةود  مَعَ أب يك الصَالِحْ ومَعَ الْرُوحْ القُدُسْ المُحْيّي المُسَاوي لك. الآنْ وكُلَّ أوانْ وإلى دَهْرِ الدُهُورْ كلها آمْينْ", 
],
[
Prefix.same+"&C=Comments", 
"", 
"يصعد الكاهن إلى الهَيْكَلْ ويضع يَدِ بَخُورفي المجمرة قائلاً:ـ", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"", 
"", 
"مجداً وإكراماً، إكراماً ومجداً للثالوث الأقدس، الآب والابن والْرُوحْ القُدُسْ. الآنْ وكُلَّ أوانْ وإلى دَهْرِ الدُهُورْ آمْينْ.", 
],
[
Prefix.same+"&C=Comments", 
"", 
"ويصعد الشماس بالإنجيل إلى الهَيْكَلْ ويعطي الكاهن البخور للإنجيل وهو دائر حول المَذْبَحْ دورة واحدة يميناً، والشماس حامل الإنجيل أمامه، ويقول الكاهن صَلاةْ سمعان الشيخ (لو 2: 29-32):", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"", 
"", 
"الآن يا سيد تطلق عبد بسلام كقولك، لِأنَّ عيني قَدّْ أبصرتا خلاصك الذي أعددته قدام جَمِيعْ الشعوب. نورا تجلى للأمم ومجداً لشعبك إسرائيل.", 
],
[
Prefix.same+"&C=Comments", 
"", 
"يقدم الكاهن كتاب البشارة لباقي الكهنة الحاضرين ليقبلوه وهو يقول:", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"", 
"", 
"أما أنتم فطوبى لأعينكم لِأنَّهُا تبصر، ولآذانكم لِأنَّهُا تسمع.", 
],
[
Prefix.same+"&C=Comments", 
"", 
"ثُمَّ يقدم الكاهن كتاب البشارة للشمامسة الحاضرين ليقبلوه وهو يقول:", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"Prosternez-vous devant l’Évangile de Jésus-Christ.", 
"", 
"اسجدوا لإنجيل يَسُوعْ المسيح", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲥⲧⲁⲑⲏⲧⲉ ⲙⲉⲧⲁ ⲫⲟⲃⲟⲩ Ⲑⲉⲟⲩ ⲁ̀ⲕⲟⲩⲥⲱⲙⲉⲛ ⲧⲟⲩ ⲁ̀ⲅⲓⲟⲩ ⲉⲩⲁ̀ⲅⲅⲉⲗⲓⲟⲩ.", 
"Levons-nous avec crainte de Dieu et soyons attentifs pour écouter le Saint Évangile.", 
"ستاثي تي ميتا فوفو ثيؤ، آكوس أومين تو آجيو إف آنجيليو.", 
"قفوا بخوف اللّه لسماع الإنجيل المُقَدَّسْ.", 
],
[
Prefix.same+"&C=Comments", 
"", 
"ثُمَّ يقف الكاهن عند باب الهَيْكَلْ ويضع كتاب البشارة على رأسه ويقول:", 
],
[
Prefix.same+"&C=Priest", 
"Ϥⲥ̀ⲙⲁⲣⲱⲟⲩⲧ ⲛ̀ϫⲉ ⲫⲏⲉⲑⲛⲏⲟⲩ ϧⲉⲛ ⲫ̀ⲣⲁⲛ ⲙ̀ⲡ̀ϭⲟⲓⲥ ⲛ̀ⲧⲉ ⲛⲓϫⲟⲙ: ⲕⲩⲣⲓⲉ̀ ⲉⲩⲗⲟⲅⲏⲥⲟⲛ ⲉⲕ ⲧⲟⲩ ⲕⲁⲧⲁ (…) ⲁⲅⲓⲟⲩ ⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲧⲟ ⲁⲛⲁⲅⲛⲱⲥⲙⲁ.", 
"Béni soit celui qui vient au Nom du Seigneur, notre Seigneur. Ô Dieu bénis la lecture de l’évangile selon Saint (…).", 
"افيسمارؤوت إنجي في إثنيو، خين افران إم إبي تشويس إنتي ني جوم، كيريه افلوغيسون إك تو كاتا (....) آجيو إف آنجليون تو آناغنوسما.", 
"مبارك الآتي باسم الرَبّ. يا رَبّ بارك الفصل من الإنجيل المُقَدَّسْ من (...).", 
],
],
[
[
Prefix.commonPrayer+"GospelIntroduction&D=$copticFeasts.AnyDay&C=Title", 
"", 
"L’Evangile", 
"", 
" الإنجيل", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲥⲧⲁⲑⲏⲧⲉ ⲙⲉⲧⲁ ⲫⲟⲃⲟⲩ Ⲑⲉⲟⲩ ⲁ̀ⲕⲟⲩⲥⲱⲙⲉⲛ ⲧⲟⲩ ⲁ̀ⲅⲓⲟⲩ ⲉⲩⲁ̀ⲅⲅⲉⲗⲓⲟⲩ.", 
"Levons-nous avec crainte de Dieu et soyons attentifs pour écouter le Saint Évangile.", 
"ستاثي تي ميتا فوفو ثيؤ، آكوس أومين تو آجيو إف آنجيليو.", 
"قفوا بخوف اللّه لسماع الإنجيل المُقَدَّسْ.", 
],
[
Prefix.same+"&C=Diacon", 
"", 
"Lecture du Saint évangile selon Saint (…) que sa bénédiction soit sur nous tous amen.", 
"", 
"فصل من بشارة الإنجيل لمعلمنا مار (....) البشير، بركاته على جميعنا آمْينْ.", 
],
[
Prefix.same+"&C=Priest", 
"Ⲡⲉⲛϭⲟⲓⲥ ⲟⲩⲟϩ ⲡⲉⲛⲛⲟⲩϯ ⲟⲩⲟϩ ⲡⲉⲛⲥⲱⲧⲏⲣ ⲟⲩⲟϩ ⲡⲉⲛⲟⲩⲣⲟ ⲧⲏⲣⲉⲛ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲡ̀ϣⲏⲣⲓ ⲙ̀ⲫ̀ⲛⲟⲩϯ ⲉⲧⲟⲛϧ ⲡⲓⲱ̀ⲟⲩ ⲛⲁϥ ϣⲁ ⲉ̀ⲛⲉϩ.", 
"Notre Seigneur, Dieu, Sauveur, et Roi de nous tous, Jésus Christ, le Fils du Dieu vivant, à qui la gloire pour toujours.", 
"بين شويس أووه بيننوتي أووه بينسوتير أووه بيننوتي تيرين إيسوس باخرستوس إبشيري إم افنوتي إتؤنخ بي أووه ناك شا إينيه.", 
"رَبّنا، والهنا، ومخلصنا، وملكنا كلنا، يَسُوعْ المسيح، ابنُ اللّه الحى، الذي لَهُ المَجْدُ للأبد.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"ZoksasiKyrie&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"PsalmIntroduction&D=$copticFeasts.AnyDay", 
],
[
Prefix.same+"&C=Diacon", 
"Ϥⲥ̀ⲙⲁⲣⲱⲟⲩⲧ ⲛ̀ϫⲉ ⲫⲏⲉⲑⲛⲏⲟⲩ ϧⲉⲛ ⲫ̀ⲣⲁⲛ ⲙ̀ⲡ̀ϭⲟⲓⲥ ⲛ̀ⲧⲉ ⲛⲓϫⲟⲙ: ⲕⲩⲣⲓⲉ̀ ⲉⲩⲗⲟⲅⲏⲥⲟⲛ ⲉⲕ ⲧⲟⲩ ⲕⲁⲧⲁ (…) ⲁⲅⲓⲟⲩ ⲉⲩⲁⲅⲅⲉⲗⲓⲟⲛ ⲧⲟ ⲁⲛⲁⲅⲛⲱⲥⲙⲁ.", 
"Béni soit celui qui vient au Nom du Seigneur, notre Seigneur, notre Dieu et Sauveur Jésus-Christ, le fils unique du Dieu Vivant, Gloire à Lui éternellement Amen.", 
"افيسمارؤوت إنجي في إثنيو، خين افران إم إبي تشويس إنتي ني جوم، كيريه افلوغيسون إك تو كاتا (....) آجيو إف آنجليون تو آناغنوسما.", 
"مبارك الآتي باسم الرَبّ، رَبّنا وإلَهْنَا ومُخَلِصّْنَا يَسُوعْ المَسِيحْ ابنُ اللّه الحي، الذي لَهُ المَجْدُ الدائم إلى الآبد آمْينْ.", 
],
[
Prefix.same+"&C=Comments", 
"Le Diacre lit l’évangile et conclut en disant : Gloire à notre Dieu éternellement, amen !", 
"يقرأ الشماس الإنجيل وفي ختامه يقول: المَجْدُ لإلَهْنَا إلى الأبَدْ آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"ZoksasiKyrie&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲇⲟⲝⲁ ⲥⲓ ⲕⲩⲣⲓⲉ", 
"Gloire à Toi, O Seigneur.", 
"ذوكساسي كيريا", 
"المجد لَكَ يا رَبّ", 
],
],
[
[
Prefix.commonPrayer+"PsalmIntroduction&D=$copticFeasts.AnyDay&C=Diacon", 
"", 
"Psaume de notre père David le prophète et le roi que sa bénédiction soit sur nous tous amen.", 
"", 
"من مزامير تراتيل أبونا داوود النبي والملك الطاهر بركاته على جميعنا آمْينْ", 
],
[
Prefix.same+"&C=Comments", 
"Le Diacre lit le psaume et à la fin l’assemblée répond : Alléluia !", 
"(يقرأ الشماس المَزْمُورْ وفي ختامه يرد الشعب: الليلويا", 
],
],
[
[
Prefix.commonPrayer+"GospelLitanyComment4&D=$copticFeasts.AnyDay&C=Comments", 
"", 
"وفي أثناء ذلك يأخذ الكاهن الصَلِيبْ من الشماس أو من فوق المذبح، ويحول وجهه إلى الشَرْقِ ويقول هَذِهِ الصلوات للأبن:ـ", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"Oui Seigneur, Seigneur, Toi qui nous a donné le pouvoir de fouler aux pieds les serpents, les scorpions et toute la puissance de l'ennemi. écrase vite leurs têtes sous nos pieds et écarte les mauvais desseins qu'ils dressent contre nous car Tu es notre Roi ô Christ notre Dieu et à Toi nous rendons gloire, honneur et adoration avec Ton Père très bon et le Saint-Esprit vivifiant et consubstantiel à Toi, Maintenant et toujours et pour les siècles des siècles. Amen.", 
"", 
"نعم يا رَبّ، يا رَبّ الذي أعطانا السلطان أنْ ندوس الحيات والعقارَبّ وكُلَّ قوة العدو، اسحق رؤوسه تحت أقدامنا سريعاً وبدد عنا كُلِّ مَعَقولاته الشريرة المقاومة لنا. لأنَّكَ أنْتَ هو ملكنا أيُّهَا المَسِيحْ إلهنا، وأنت الذي نرسل لَكَ إلى فوق المَجْدُ والكَرَامَةْ والسجةود  مَعَ أب يك الصَالِحْ ومَعَ الْرُوحْ القُدُسْ المُحْيّي المُسَاوي لَكَ الآنْ وكُلَّ أوانْ وإلى دَهْرِ الدُهُورْ كلها آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"BlockInTheNameOfOurLord&D=$copticFeasts.AnyDay&C=Diacon", 
"Ϧⲉⲛ Ⲡⲭ̅ⲥ̅ Ⲓⲏ̅ⲥ̅ ⲡⲉⲛϭⲟⲓⲥ.", 
"Par le Christ Jesus notre Seigneur.", 
"خين باخرستوس إيسوس بينشويس", 
"بِالْمَسِيحْ يَسُوعْ رَبّنا.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲧⲁⲥ ⲕⲉⲫⲁⲗⲁⲥ ⲩ̀ⲙⲱⲛ ⲧⲱ Ⲕⲩⲣⲓⲱ ⲕ̀ⲗⲓⲛⲁⲧⲉ.", 
"Inclinez vos têtes devant Le Seigneur.", 
"تاس كي فالاسيمون تو كيريو إكليناتي", 
"احنوا رؤوسكم للرَبّ.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲉⲛⲱⲡⲓⲟⲛ ⲥⲟⲩ Ⲕⲩⲣⲓⲉ̀.", 
"Devant Toi, Seigneur.", 
"انوبيون سو كيريا", 
"أمامك يا رَبّ خاضعين وساجدين.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲡⲣⲟⲥⲭⲱⲙⲉⲛ Ⲑⲉⲟⲩ ⲙⲉⲧⲁ ⲫⲟⲃⲟⲩ: ⲁ̀ⲙⲏⲛ.", 
"Soyons attentifs dans la crainte de Dieu. Amen.", 
"ابروس خومين ثيؤو ميتا فوفو آمْينْ.", 
"انصتوا بخوف اللّه. آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"GospelLitanyComment5&D=$copticFeasts.AnyDay&C=Comments", 
"", 
"وفي أثناء ذلك يأخذ الكاهن الصَلِيبْ من الشماس أو من فوق المذبح، ويحول وجهه إلى الشَرْقِ ويقول هَذِهِ الصلوات للأبن:ـ", 
],
[
Prefix.same+"&C=CommentText", 
"", 
"Toi, Seigneur, qui as abaissé les cieux, qui en es descendu et T'es fait homme pour le Salut du genre humain, Toi qui siéges au dessus des Chérubins et des Séraphins en regardant les humbles. Toi aussi, notre Maître, vers qui nous élevons les yeux de nos coeurs, Tu remets, Seigneur, nos péchés et sauves nos âmes de la corruption. Nous nous prosternons devant Ta tendresse ineffable et nous Te supplions de nous donner Ta paix, car Tu nous as tout donné. Rachète-nous, ô Dieu notre Sauveur, car nous ne connaissons aucun autre que Toi et nous invoquons Ton Saint Nom. Ramène-nous, ô Dieu, à Ta crainte et Ton désir et fais que nous béné fissions de Tes bienfaits. Ceux qui ont incliné. leurs têtes sous Ta main fais-les progresser dans leur vie spirituelle, orne-les de vertus. Puissions-nous être tous dignes de Ton Royaume qui est dans les cieux selon la volonté de Ton Père très bon Avec qui Tu es béni ainsi que le Saint-Esprit vivifiant et consubstantiel à Toi. Maintenant et toujours et pour les siècles des siècles. Amen", 
"", 
"أنت يا رَبّ الذي طأطأت السَّمَواتْ ونزلت وتأنست من أجل خلاص جنس البشر، أنْتَ هو الجالس على الشاروبيم والسيرافيم والناظر إلى المتواضعين.. أنْتَ أيضاً الآنْ يا سَيِّدنْا الذي نرفع أعين قلوبنا إليَكَ أيُّهَا الرَبّ الغافر آثامنا ومخلص نفوس نا من الفساد، نسجد لتعطفك الذي لا ينطق به ونسألك أنْ تعطينا سلامك لأنَّكَ أعطيتنا كُلِّ شيء. اقتننا لَكَ يا اللّه مُخَلِصّْنَا لأننا لا نعرف آخر سِواكْ. اسمك القُدُّوسْ هو الذي نقوله. ردنا يا اللّه إلى خوفك وشوقك، مر أنْ نتمتع بخيراتك. والذين أحنوا رؤسهم تحت يدك، ارفعهم في السيرة، زينهم بالفضائل، ولنستحق كلنا مَلَكُوتَكْ الذي في السَّمَواتْ بمسرة أبيك الصالح. هَذا الذي أنْتَ مُبَارَكْ مَعَه ومَعَ الْرُوحْ القُدُسْ المُحْيّي المُسَاوي لَكَ الان وكُلَّ أوانْ وإلى دَهْرِ الدُهُورْ كلها آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"AbsolutionForTheSon&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Absolution du Fils", 
"", 
" تحليل الابن", 
],
[
Prefix.same+"&C=Priest", 
"", 
"Ô Maître Seigneur Jésus Christ Fils unique de Dieu et Logos du Père qui nous a délié de tous les liens du péché par Sa souffrance salvatrice et vivifiante, qui a soufflé sur le visage de Ses saints disciples et purs apôtres, en leur disant: “Recevez L’Esprit Saint. Ceux à qui vous pardonnerez les péchés, ils leur seront pardonnés, et ceux à qui vous les retiendrez, ils leur seront retenus.”", 
"", 
"أَيُّهَااَلسيد الرَبّ يَسُوعْ المَسِيحْ ابنُ اللّه الوَحِيد وكُلَّمة الآب الذي قطع كُلِّ رَبّاطات خَطَايَانَا من قبل آلامه المخلصة المحيية٬ الذي نفخ في وَجْهْ تلاميذه القِدِّيسِينْ ورسله الأطهار وقال لهم اقبلوا الْرُوحْ القُدُسْ من غفرتم خطاياهم غُفرت ومن أمسكتموها عَليهُم أمسكت .", 
],
[
Prefix.same+"&C=Priest", 
"", 
"Toi, encore maintenant, notre Seigneur par l’intermédiaire de Tes purs apôtres Tu as accordé en tout temps à ceux qui œuvrent dans le sacerdoce de Ton église sainte de pardonner les péchés sur terre et de lier et délier tous les liens du mal.", 
"", 
"أنت الآنْ ياسيدنا من قبل رسلك الأطهار أنعمت على الذين يعملون في الكهنوت كُلِّ زمان في كَنِيسَتَكْ المُقَدَّسْة أنْ يغفروا الخطايا على الأرْضْ ويرَبّطوا ويحلوا كُلِّ رَبّاطات الظلم.", 
],
[
Prefix.same+"&C=Priest", 
"", 
"Maintenant encore nous prions et réclamons dans Ta bonté, O Philanthrope pour Tes serviteurs mes pères, mes frères et ma faiblesse, ceux-ci qui ont incliné leurs têtes devant Ta sainte gloire.", 
"", 
"الآن أيضاً نسأل ونَطْلُبْ من صلاحك يا مُحِبْ الَبشَرْ عن عبيدك آبائى وإخواتى وضعفى هؤلاء المنحنين برؤسهم أمام مَجْدَكْ المُقَدَّسْ.", 
],
[
Prefix.same+"&C=Priest", 
"", 
"Accorde-nous Ta miséricorde et coupe tous les liens de nos péchés, et si nous avons péché à Ton égard consciemment ou inconsciemment par panique ou par faiblesse du cœur, par un acte, ou par une parole ou par rapetissement du cœur. Toi Seigneur, qui connait les faiblesses des hommes, bon et Philanthrope, O Dieu accorde-nous la rémission de nos péchés.", 
"", 
"ارزقنا رَحْمَتُكَ واقطع كُلِّ رَبّاطات خَطَايَانَا٬ وإن كنا اخطأنا إليَكَ في شئ بعلم أو بِغَيْر علم  أو بجزع القلب أوبالفعل أو بالقول أوبصغر القلب ٬ فأنت أيُّهَا السيد العارف بضعف الَبشَرْ كصالح ومحب الَبشَرْ اَللَّهُمَّ انْعِمْ عَلَيْنَا بغفران خَطَايَانَا .", 
],
[
Prefix.same+"&C=Priest", 
"", 
"Bénis-nous, purifie-nous, donne-nous l’absolution, et absous tout Ton peuple. Remplis-nous de Ta crainte, et ressuscite-nous selon Ta sainte volonté.", 
"", 
"باركنا طهرنا حاللنا وحالل سَائِرْ شعبك. املأنا من خوفك وقوّمنا إلى إرادتك المُقَدَّسْة الصالحة", 
],
[
Prefix.same+"&C=Priest", 
"", 
"Car Tu es notre Seigneur qui mérite la gloire, la dignité, la richesse et l’adoration avec Ton bon Père et Le Saint Esprit vivifiant et consubstantiel avec Toi, maintenant, toujours et dans les siècles des siècles. Amen.", 
"", 
"لأنك أنْتَ إلَهْنَا ويليق بك المَجْدُ والكَرَامَةْ والعزة و السُجُودْ  مَعَ أبِيكَ الصَالِحْ والْرُوحْ القُدُسْ المُحْيّي المُسَاوي لَكَ الآنْ وكُلَّ أوانْ وإلى دَهْرِ الدُهُورْ آمْينْ.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"KyrieEliesonThreeTimes&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"ConcludingHymn&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Hymne de la fin", 
"", 
" الصلاة الختامية (آمين الليلويا)", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲁ̀ⲙⲏⲛ Ⲁⲗ̅: Ⲇⲟⲝⲁ ⲡⲁⲧⲣⲓ ⲕⲉ Ⲩ̀Ϯⲓⲱ ⲕⲉ ⲁⲅⲓⲱ Ⲡ̀ⲛⲉⲩⲙⲁⲧⲓ: ⲕⲉ ⲛⲩⲛ ⲕⲉ ⲁ̀ⲓ̀ ⲕⲉ ⲓⲥ ⲧⲟⲩⲥ ⲉ̀ⲱ̀ⲛⲁⲥ ⲧⲱⲛ ⲉ̀ⲱ̀ⲛⲱⲛ: ⲁ̀ⲙⲏⲛ. Ⲧⲉⲛⲱϣ ⲉ̀ⲃⲟⲗ ⲉⲛϫⲱ ⲙ̀ⲙⲟⲥ ϫⲉ ⲱ̀ Ⲡⲉⲛϭⲟⲓⲥ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅:", 
"Amen! Alléluia. Gloire soit au Père, au Fils et au Saint Esprit, maintenant et toujours et dans les siècles. Amen! Nous clamons en disant: ô Notre Seigneur Jésus Christ.", 
"آمين الليلويا، ذوكسا باتري كي إيو كي آجيو ابنيفماتي، كي نين كي آ إي كي ايس توس إي أوناس تون إي أونون آمْينْ. تين أوشت إيفول إنجو إموس، جي أو بينتويس إيسوس باخريستوس.", 
"آمين هلليلويا. المَجْدُ للآب والابن والْرُوحْ القُدُسْ، الآنْ وكُلَّ أوانْ وإلي دَهْرِ الدِهُورْ. آمْينْ. نصرخ قائلين: يا رَبّنا يَسُوعْ المسيح.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲁϥⲧⲱⲛϥ ⲉ̀ⲃⲟⲗ ϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ ϧⲉⲛ ⲡⲓⲉ̀ϩⲟⲟⲩ. Ⲙⲁⲣⲉ ⲡⲉⲕⲛⲁⲓ ⲛⲉⲙ ⲧⲉⲕϩⲓⲣⲏⲛⲏ ⲟⲓ ⲛ̀ⲥⲟⲃⲧ ⲙ̀ⲡⲉⲕⲗⲁⲟⲥ: Ⲥⲱϯ ⲙ̀ⲙⲟⲛ ⲟⲩⲟϩ ⲛⲁⲓ ⲛⲁⲛ:", 
"le roi de gloire est résuscité le troisième jour. Que Ta miséricorde et Ta paix soient un rampart pour Ton peuple. Sauve-nous et aie pitié de nous.", 
"إبؤورو إنتي إبؤ أو آفطونف إيفول خين نيئثُمَّوؤت. ماري بيك ناي نيم تيك هيريني أوي إنسوتب إمبيلاؤس، سوتي إممون أووه ناي نان.", 
"ملك المَجْدُ قام من بين الأموات. فلتكن رَحْمَتُكَ وسلامك حصنا لشعبك خلصنا وإرحمنا.", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲕⲩⲣⲓⲉ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ ⲉⲩⲗⲟⲅⲏⲥⲟⲛ: ⲁ̀ⲙⲏⲛ: ⲥ̀ⲙⲟⲩ ⲉ̀ⲣⲟⲓ:", 
"Pitié Seigneur, pitié Seigneur, Seigneur bénis nous, amen.", 
"كيريالَيسون، كيريالَيسون، كيريه إيفلوغيسون آمْينْ", 
"يا رَبّ ارحم، يارَبّ، ارحم، يا رَبّ بارك آمْينْ.", 
],
[
Prefix.same+"&C=Assembly", 
"ⲥ̀ⲙⲟⲩ ⲉ̀ⲣⲟⲓ: ⲓⲥ ϯⲙⲉⲧⲁⲛⲟⲓⲁ: ⲭⲱ ⲛⲏⲓ ⲉ̀ⲃⲟⲗ ϫⲱ ⲙ̀ⲡⲓⲥ̀ⲙⲟⲩ.", 
"Bénissez-moi, voici la métanoia, dites la bénédiction.", 
"اسمو إروي، إمو إروي، ايس تي ميتانيا كوني إيفول كو إمبي اسمو.", 
"باركوا على، ها المطانية، اغفروا لى، قل البركة.", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"OJesusChristOurGod&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"AssemblyResponseAmeenItWillBe&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"Kyrielison41TimesMassIntro&D=$copticFeasts.AnyDay&C=Priest", 
"", 
"Agneau de Dieu qui porte les péchés, du monde, nous T'implorons écoute nous et aie pitié de nous", 
"", 
"نسألك يا حمل اللّه يا حامل خطية العالم اسمعنا وارْحَمْنَا واغْفِرْ لَنَا خَطَايَانَا آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"Kyrielison41TimesNoMassIntro&D=$copticFeasts.AnyDay&C=Priest", 
"", 
"Agneau de Dieu qui porte les péchés, du monde, nous T'implorons écoute nous et aie pitié de nous", 
"", 
"نسألك يا رَبّ اسمعنا وارْحَمْنَا واغْفِرْ لَنَا خَطَايَانَا آمْينْ.", 
],
],
[
[
Prefix.commonPrayer+"Kyrielison41Times&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ: Ⲕⲩⲣⲓⲉ̀ ⲉ̀ⲗⲉⲏ̀ⲥⲟⲛ:", 
"Pitié Seigneur. 41 fois Aie pitié ô Dieu Écoute et aie pitié de nous", 
"كيريالَيسون (41)", 
"يا رَبّ ارحم (41 مرة) ارْحَمْنَا يااللّه، اسمعنا وارْحَمْنَا", 
],
],
[
[
Prefix.commonPrayer+"HolyHolyHolyLordOfSabaot&D=$copticFeasts.AnyDay&C=SubTitle", 
"", 
"Saint, Saint, Saint Seigneur sabaot", 
"", 
" قُدُّوسْ، قُدُّوسْ، قُدُّوسْ، رَبّ الصباؤوت", 
],
[
Prefix.same+"&C=Assembly", 
"ⲋ̀ⲟⲩⲁⲃ ⲋ̀ⲟⲩⲁⲃ ⲋ̀ⲟⲩⲁⲃ Ⲡⲟ̅ⲥ̅ ⲙ̀ⲡⲓⲥⲁⲃⲁⲱϯ ⲧ̀ⲫⲉ ⲛⲉⲙ ⲡ̀ⲕⲁⲏⲓ ⲙⲉⲏ ⲉⲃⲟⲗⲑⲉⲛ ⲡⲉⲕⲱⲟⲩ ⲛⲉⲙ ⲡⲉⲕⲧⲁⲓⲟ. Ⲉⲗⲉⲯ̀ⲥⲟⲛ ⲯ̀ⲙⲁⲥ ⲟ̀ Ϯⲉⲟⲥ ⲟ̀ Ⲡⲁⲧⲯⲣ ⲟ̀ Ⲡⲁⲛⲧⲟⲕⲣⲁⲧⲱⲣ+ ⲡⲁⲛⲁ̀ⲅⲓⲁ ⲧ̀ⲣⲓⲁⲥ ⲉ̀ⲗⲉⲯ̀ⲥⲟⲛ ⲯ̀ⲙⲁⲥ. Ⲡⲟ̅ⲥ̅ Ⲫϣ ⲛ̀ⲧⲉ ⲛⲓϫⲟⲙ ϭⲱⲡⲓ ⲛⲉⲙⲁⲛ ϫⲉ ⲙ̀ⲙⲟⲛ ⲛ̀ⲧⲁⲛ ⲛ̀ⲟⲩⲃⲟⲯϯⲟⲥ ⲑⲉⲛ ⲛⲉⲛ ϯ̀ⲗⲓϧⲓⲥ ⲛⲉⲙ ⲛ̀ⲏⲟϫⲏⲉϫ ⲉⲃⲯⲗ ⲉⲣⲟⲕ.", 
"Saint, Saint, Saint Seigneur sabaot, le ciel et la terre sont remplis de Ta gloire et de ton honneur. Pitié pour nous ô Dieu le Père tout puissant. Pitié pour nous ô Trinité Sainte. Ô Seigneur Dieu des puissances sois avec nous, car nous n’attendons d’aide que de toi dans nos difficultés et nos angoisses .", 
"", 
"قُدُّوسْ، قُدُّوسْ، قُدُّوسْ، رَبّ الصباؤوت. السَّمَاء والأرض مملوءتان من مَجْدَكْ وكرامتك. ارْحَمْنَا يااللّه الآب ضَابِطْ الكُلّ. أيُّهَا الثَالُوثْ القُدُّوسْ ارْحَمْنَا. أيُّهَا الرَبّ إله القوات كن مَعَنا، لِأنَّهُ لَيْسَ لنا مَعَين في شَدَائِدْنَا وضيقاتنا سِواكْ", 
],
[
Prefix.same+"&C=Assembly", 
"Ⲃⲱⲗ ⲉⲃⲟⲗ ⲋⲱ ⲉⲃⲟⲗ ⲁⲣⲓⲥⲩⲛⲋⲱⲣⲓⲛ ⲛⲁⲛ Ⲫϣ ⲛ̀ⲛⲉⲛⲡⲁⲣⲁⲡⲧⲱⲙⲁ ⲛⲯⲉⲧⲁⲛⲁⲓⲧⲟⲩ ⲑⲉⲛ ⲡⲉⲛⲟⲩⲱϭ ⲛⲉⲙ ⲛⲯⲉⲧⲁⲛⲁⲓⲧⲟⲩ ⲑⲉⲛ ⲡⲉⲛⲟⲩⲱϭ ⲁⲛ ⲛⲯⲉⲧⲁⲛⲁⲓⲧⲟⲩ ⲑⲉⲛ ⲟⲩⲉⲙⲓ ⲛⲉⲙ ⲛⲯⲉⲧⲁⲛⲁⲓⲧⲟⲩ ⲑⲉⲛ ⲟⲩⲙⲉⲧⲁⲧⲉⲙⲓ ⲛⲯⲉⲧⲏⲯⲡ ⲛⲉⲙ ⲛⲯⲉϯⲟⲩⲱⲛⲏ ⲉⲃⲟⲗ Ⲡⲟ̅ⲥ̅ ⲋⲁⲩ ⲛⲁⲛ ⲉⲃⲟⲗ ⲉϯⲃⲉ ⲡⲉⲕⲣⲁⲛ ⲉ̅ϯ̅ⲩ ⲉⲧⲁⲩⲙⲟⲩϣ ⲙ̀ⲙⲟϥ ⲉ̀ⲏ̀ⲣⲯⲓ Ⲕⲁⲧⲁ ⲧⲟ ⲉ̀ⲗⲉⲟⲥ ⲥⲟⲩ Ⲕⲩⲣⲓⲉ+ ⲕⲉ ⲙⲯ ⲕⲁⲧⲁ ⲧⲁⲥ ⲁ̀ⲙⲁⲣⲧⲓⲁⲥ ⲯ̀ⲙⲱⲛ.", 
"Ô Dieu délie, pardonne et remets nos péchés; ceux que nous avons commis volontairement ou involontairement, consciemment ou inconsciemment, secrètement ou en public. Ô Seigneur pardonne les nous à cause de Ton saint Nom qui a été invoqué sur nous. Selon Ta miséricorde Seigneur et non selon nos péchés.", 
"", 
"حل واغفر واصفح لنا يا اللّه عن سيئاتنا، التي صنعناها بإرادتنا والتي صنعناها بِغَيْر إرادتنا، التي فعلناها بمعرفة والتي فعلناها بِغَيْر مَعَرفة، الخفية والظاهرة. يا رَبّ اغفرها لنا، من أجل اسمك القُدُّوسْ الذي دعي عَلَيْنَا كرحمتك يا رَبّ ولَيس كخطايانا.", 
],
],
[
[
Prefix.commonPrayer+"WeHaveBeenSavedWithYou&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲥⲱⲑⲓⲥ ⲁ̀ⲙⲏⲛ: ⲕⲉ ⲧⲱ ⲡ̀ⲛⲉⲩⲙⲁⲧⲓ ⲥⲟⲩ.", 
"Nous avons été sauvés, en vérité, et avec ton esprit.", 
"سويس آمْينْ، كي تو ابنيفماتي سو", 
"خلصتَ حقاً ومَعَ روحِكَ.", 
],
],
[
[
Prefix.commonPrayer+"AmenWeBelieve&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲁⲙⲏⲛ: ϯⲛⲁϩϯ.", 
"Amen, nous croyons.", 
"", 
"حقاً نؤمن.", 
],
],
[
[
Prefix.commonPrayer+"BlockShlilIriniPassi&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"BlockShlil&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.commonPrayer+"BlockIriniPassi&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.commonPrayer+"AssemblyResponseAndWithYourSoul&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲕⲉ ⲧⲱ ⲡ̀ⲛⲉⲩⲙⲁⲧⲓ ⲥⲟⲩ.", 
"Et avec votre esprit.", 
"", 
"ومع روحِكَ أيضاً.", 
],
],
[
[
Prefix.commonPrayer+"OJesusChristOurGod&D=$copticFeasts.AnyDay&C=Priest", 
"Ⲡⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ.", 
"Ô Christ notre Dieu.", 
"", 
"أَيُّهَااَلمَسِيحْ الهنا.", 
],
],
[
[
Prefix.commonPrayer+"AssemblyResponseAmeenItWillBe&D=$copticFeasts.AnyDay&C=Assembly", 
"Ⲁⲙⲏⲛ ⲉⲥⲉ̀ϣⲱⲡⲓ.", 
"Amen, ainsi soit-il.", 
"", 
"آمين يكون.", 
],
],
[
[
Prefix.commonPrayer+"HeToWhomGloryIsDue&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲫⲁⲓ ⲉ̀ⲣⲉ ⲡⲓⲱ̀ⲟⲩ ⲉⲣⲡ̀ⲣⲉⲡⲓ ⲛⲁϥ: ⲛⲉⲙ Ⲡⲉϥⲓⲱⲧ ⲛ̀ⲁ̀ⲅⲁⲑⲟⲥ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ: ⲓⲥϫⲉⲛ ϯⲛⲟⲩ ⲛⲉⲙ ϣⲁ ⲉ̀ⲛⲉϩ.", 
"Lui à qui est due la gloire Avec Son Père Très-Bon Et avec le Saint-Esprit Maintenant et à jamais.", 
"فاي إيريبى أو أو إير إبريبى ناف♫ نيم بيف يوت إن آغاثوس♫ نيم بى ابنفما إثؤواب♫ يسجين تينو نيم شا إنيه.", 
"هذا الذي ينبغي لَهُ المَجْدُ♫ َمَعَ أبيهِ الصالح♫ والروح القُدُس♫ من الآنْ وإلى الأبد.", 
],
],
];