CymbalVersesPrayersArray= [[
[
Prefix.cymbalVerses+"Wates&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Cymbals Verses Adam", 
"", 
" أرَبّاع الناقوس واطس", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲧⲉⲛⲟⲩⲱϣⲧ ⲙ̀Ⲫ̀ⲓⲱⲧ ⲛⲉⲙ Ⲡ̀ϣⲏⲣⲓ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ: Ϯⲧ̀ⲣⲓⲁⲥ ⲉⲑⲟⲩⲁⲃ: ⲛ̀ⲟ̀ⲙⲟⲟⲩⲥⲓⲟⲥ", 
"Nous adorons le Père,♫ le Fils, et le Saint-Esprit♫, trinité Sainte, et consubstantielle.", 
"تين أوؤشت إم افيوت نيم ابشيري♫ نيم ني ابنيفما اثؤواب♫ تيترياس اثؤواب إن أوموسيوس.", 
"نسجد للآب والابن♫ والْرُوحْ القُدُسْ♫ الثَالُوثْ، القُدُّوسْ، المساوي في الجوهر.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ ϯⲉⲕⲕ̀ⲗⲏⲥⲓⲁ: ⲡ̀ⲏⲓ ⲛ̀ⲧⲉ ⲛⲓⲁⲅⲅⲉⲗⲟⲥ: ⲭⲉⲣⲉ ϯⲡⲁⲣⲑⲉⲛⲟⲥ: ⲉ̀ⲧⲁⲥⲙⲉⲥ Ⲡⲉⲛⲥⲱⲧⲏⲣ.", 
"Salut à l’Église,♫ la maison des anges.♫ Salut à la vierge qui a enfanté notre Sauveur", 
"شيري تي إكلَيسيا♫ بي إنتي ني آنجيلوس♫ شيري تي بارثينوس إيتاسميس بينسوتير.", 
"السَّلامُ للكنيسة♫ بيت الملائكة♫ السَّلامُ، للعذراء، التي، ولدت، مخلصنا.", 
],
],
[
[
Prefix.cymbalVerses+"Adam&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Cymbals Verses Adam", 
"", 
" أرَبّاع الناقوس آدام", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁⲙⲱⲓⲛⲓ ⲙⲁⲣⲉⲛⲟ̀ⲩⲱϣⲧ: ⲛ̀Ϯⲧ̀ⲣⲓⲁⲥ ⲉⲑⲟⲩⲁⲃ: ⲉ̀ⲧⲉ ⲫ̀Ϯⲓⲱⲧ ⲛⲉⲙ ⲡ̀ϣⲏⲣⲓ: ⲛⲉⲙ ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ.", 
"Venez, prosternons-nous♫ Pour la Sainte Trinité♫ qui est le Père, Fils♫ et l’Esprit-Saint.", 
"آمويني مارين أؤوشت♫ إن تي اترياس اثؤواب♫ إتي فيوتي نيم ابشيري نيم بي ابنيفما اثؤواب.", 
"تعالوا فلنسجد♫ للثالوث القُدُّوسْ♫ الذي هو الآب والابن♫ والْرُوحْ القُدُسْ.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁⲛⲟⲛ ϧⲁ ⲛⲓⲗⲁⲟⲥ: ⲛ̀ⲭ̀ⲣⲓⲥⲧⲓⲁⲛⲟⲥ: ⲫⲁⲓ ⲅⲁⲣ ⲡⲉ ⲡⲉⲛⲛⲟⲩϯ: ⲛ̀ⲁ̀ⲗⲏⲑⲓⲛⲟⲥ.", 
"Nous les peoples Chrétiens♫ car il est notre♫ Dieu En vérité.", 
"آنون خا ني لاؤس♫ إن اخرستيانوس♫ فاي غار بي بينوتي إن آليثينوس.", 
"نحن الشعوب♫ المسيحيين♫ لِأنَّ هَذا هو إلهنا♫ الحقيقي.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲟⲩⲟ  ⲛ ⲟⲩϩⲉⲗⲡⲓⲥ ⲛ̀ⲧⲁⲛ: ϧⲉⲛ ⲑⲏⲉ̀ⲑⲟⲩⲁⲃ Ⲙⲁ ⲣ ⲓⲁ: ⲉ̀ⲣⲉ ⲫ̀ⲛⲟⲩϯ ⲛⲁⲓ ⲛⲁⲛ: ϩⲓⲧⲉⲛ ⲛⲉⲥⲡ̀ⲣⲉⲥⲃⲓⲁ", 
"Nous espérons♫ en Sainte Marie♫ que Dieu aie pitié de nous par son intercession.", 
"أو   أون أو هلبيس إنتان♫ خين ثي إثؤواب ماريا♫  إ ري فنوتي ناي نان هيتين ني ابريسفيا.", 
"لنا رجاء في♫ القِدِّيسَةْ مريم♫ اللّه يَرْحَمَنَا بِشَفَاعَاتْها.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲟⲩⲟⲛ ⲟⲩⲙⲉⲧⲥⲉⲙⲛⲟⲥ: ⲛ̀ϩ̀ⲣⲏⲓ ϧⲉⲛ ⲡⲓⲕⲟⲥⲙⲟⲥ: ⲉ̀ⲃⲟⲗϩⲓⲧⲉⲛ ⲡⲓϣ̀ⲗⲏⲗ: ⲛ̀ⲧⲉ ϯⲁⲅⲓⲁ Ⲙⲁⲣⲓⲁ̀ ϯⲡⲁⲣⲑⲉⲛⲟⲥ.", 
"Tout calme dans le monde♫ est dû à la prière♫ de la sainte vierge Marie.", 
"أو أون أوميت سيمنوس♫ إن إهري جين بي كوسموس♫ إفول هيتين بي إشلال إنتي تي آجيا ماريا تي بارثينوس.", 
"كل هدوء في♫ العالم من قبل♫ صَلاةْ القِدِّيسَةْ♫ مريم العذراء.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.Apostles&C=Title", 
"", 
"Fête des Apôtres", 
"", 
"أرَبّاع الناقوس لعيد الرسل", 
],
[
Prefix.same+"&C=Title", 
"Xere na_ `nio;> `napoctoloc> xere nimaqhthc> `nte Pen_ Ihcouc Pi`xrictoc.", 
"", 
"شيرى ناشويس إنيوتى: ان أبوسطولوس: شيرى نى ما سيتيس انتى بينشويس ايسوس بخرستوس.", 
" السَّلامُ لسادتى الآبَاءْ الرُسُلْ السَّلامُ لتلاميذ رَبّنا يَسُوعْ المسيح", 
],
[
Prefix.same+"&C=Title", 
"Xere peniwt Petroc> nem penca' Pauloc> nini]; `n`ctulloc> ettajro `nnipictoc.", 
"", 
"شيرى بينيوت بيتروس: نيم بينساخ بافلوس: بى نيشتى ان استيلوس: إتاجرو انى بيستوس", 
"السَّلامُ لأبينا بطرس ومعلمنا بولس العمودين العظيمين لثبات المؤمنين", 
],
[
Prefix.same+"&C=Title", 
"Xere nak `w pimarturoc> xere pieuaggelicthc> xere pi`apoctoloc> abba Markoc piqe`wrimoc.", 
"", 
" شيرى ناك أو بى مارتيروس: شيرى بى أف أنجيلَيستيس شيرى بى آبوسطولوس: ماركوس بيثيئوريموس", 
"السَّلامُ لَكَ أيُّهَا الشَهِيدْ السَّلامُ للإنجيلى السَّلامُ للرسول مرقس ناظر الإله", 
],
[
Prefix.same+"&C=Title", 
"Xere peniwt abba Markoc> pieuaggelicthc> pirefjwr `ebol> `nte ni`idwlon.", 
"", 
"شيرى بينيوت ماركوس: بى إف اجيلَيستيس بى ريف جور إيفول : انتى نى إيزولون.", 
"السَّلامُ لأبينا مرقس الإنجيلى مبدد الأوثان.", 
],
[
Prefix.same+"&C=Title", 
"Pini]; `nrefiwi]> 'en ;xwra `nte Xhmi> abba Markoc pi`apoctoloc> pec]orp `nreferemi.", 
"", 
"بى نيشتى انريفهيؤويش: خين تى كورا انتى كيمى: ماركوس بى آبوسطولوس: بيسشورَبّ انريف إرنهيمى.", 
"لمبشر العظيم في كورة مصر مرقس الرسول مدبرها الأول.", 
],
[
Prefix.same+"&C=Title", 
"Siouwini siouwini> `w ;xwra `nte Xhmi> je af`i `nje peouwini> 'en oumetlamproc.", 
"", 
"  انشيئو أوينى اتشينو: أوينى أوتى كورا إنتى كيمى: جى أفئى انجى بى أو اوينى: خين أوميت لام إبروس.", 
"نورى نورى يا كورة مصر لِأنَّهُ قَدّْ أتى نورك بضياء.", 
],
[
Prefix.same+"&C=Title", 
"Xere Iwannhc> pieuaggelicthc> xere picwtp `mparqenoc> ouo piqe`ologoc.", 
"", 
"شيرى يؤانس: بى إف إنجيلَيستيس: شيرى بى سوتب إم بارثينوس: أووه بى ثيؤلوغوس.", 
"السَّلامُ ليوحنا الإنجيلي السَّلامُ للبتول المختار الناطق بالإلهيات", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Suite Versés du Cymbal", 
"", 
"تابع أرَبّاع الناقوس", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMary&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMaykel&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"SheroubimSerafim&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StJohnBaptist&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"Apostles&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMarc&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StSteven&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StGeorge&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StTheodor&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMarcorious&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMina&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"End&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.cymbalVerses+"StMary&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲉ Ⲙⲁⲣⲓⲁ: ϯϭ̀ⲣⲟⲙⲡⲓ ⲉⲑⲛⲉⲥⲱⲥ: ⲑⲏⲉ̀ⲧⲁⲥⲙⲓⲥⲓ ⲛⲁⲛ: ⲙ̀Ⲫ̀ⲛⲟⲩϯ ⲡⲓⲗⲟⲅⲟⲥ.", 
"Salut à toi Marie♫ la belle colombe♫ Celle qui a enfanté pour nous Dieu le Verbe", 
"شيري ني ماريا♫ تي إتشرومبي إثنيسوس♫ ثي إيتاسميسي نان إم افنوتي بي لوغوس.", 
"السَّلامُ لَكَ يا مريم♫ الحمامة الحسنة♫ التي، ولدت لنا، اللّه الكلمة.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲉ Ⲙⲁⲣⲓⲁ: ϧⲉⲛ ⲟⲩⲭⲉⲣⲉ ⲉϥⲟⲩⲁⲃ: ⲭⲉⲣⲉ ⲛⲉ Ⲙⲁⲣⲓⲁ: ⲑ̀ⲙⲁⲩ ⲙ̀ⲫⲏⲉⲑⲟⲩⲁⲃ.", 
"Salut à toi Marie♫ un saint salut. Salut à toi Marie♫ La mère du Saint.", 
"شيري ني ماريا♫ خين أوشيري افؤواب♫ شيري ني ماريا اثُمَّاف إمفي اثؤواب.", 
"السَّلامُ لَكَ يا مريم♫ سَلامْ مقدس♫ السَّلامُ لَكَ يا مريم، ام القُدُّوسْ.", 
],
],
[
[
Prefix.cymbalVerses+"StMaykel&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲙⲓⲭⲁⲏⲗ: ⲡⲓⲛⲓϣϯ ⲛ̀ⲁⲣⲭⲓⲁⲅⲅⲉⲗⲟⲥ: ⲭⲉⲣⲉ Ⲅⲁⲃⲣⲓⲏⲗ: ⲡⲓⲥⲟⲧⲡ ⲙ̀ⲡⲓϥⲁⲓϣⲉⲛⲛⲟⲩϥⲓ", 
"Salut à Michel♫ le grand archange♫ Salut à Gabriel, l’annonciateur élu.", 
"شيري ميخائيل♫ بينيشتي إن أرشي أنجيلوس♫ شيري غابرييل بيسوتب إمبي فاي شينوفي.", 
"السَّلامُ لميخائيل♫ رئيس المَلائِكَةْ العظيم♫ السَّلامُ لغبريال، المبشر المختار.", 
],
],
[
[
Prefix.cymbalVerses+"SheroubimSerafim&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲓⲭⲉⲣⲟⲩⲃⲓⲙ: ⲭⲉⲣⲉ ⲛⲓⲥⲉⲣⲁⲫⲓⲙ: ⲭⲉⲣⲉ ⲛⲓⲧⲁⲅⲙⲁ ⲧⲏⲣⲟⲩ: ⲛ̀ⲉ̀ⲡⲟⲩⲣⲁⲛⲓⲟⲛ.", 
"Salut aux Chérubins♫ salut aux Séraphins♫ salut à tous les grades célestes.", 
"شيري شيروبيم♫ شيري ني سيرافيم♫ شيري ني طاغما تيرو إن إيبورانيون.", 
"السَّلامُ للشاروبيم♫ السَّلامُ للسيرافيم♫ السَّلامُ، لجميع، الطغمات، السَمَائِيَّة.", 
],
],
[
[
Prefix.cymbalVerses+"StJohnBaptist&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲓⲱⲁⲛⲛⲏⲥ: ⲡⲓⲛⲓϣϯ ⲙ̀ⲡ̀ⲣⲟⲇⲣⲟⲙⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲟⲩⲏⲃ: ⲡ̀ⲥⲩⲅⲅⲉⲛⲏⲥ ⲛ̀Ⲉⲙⲙⲁⲛⲟⲩⲏⲗ", 
"Salut à Jean♫ le grand précurseur♫ salut au prêtre, Parent d'Emmanuel.", 
"شيري يوآنس♫ بي نيشتي إبروذروموس♫ شيري بيؤويف إبسنجنيس إن إمانوئيل.", 
"السَّلامُ ليوحنا♫ السابق العظيم♫ السَّلامُ، للكاهن، نسيب، عمانوئيل.", 
],
],
[
[
Prefix.cymbalVerses+"Apostles&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲁϭⲟⲓⲥ ⲛ̀ⲓⲟϯ: ⲛ̀ⲁ̀ⲡⲟⲥⲧⲟⲗⲟⲥ: ⲭⲉⲣⲉ ⲛⲓⲙⲁⲑⲏⲧⲏⲥ: ⲛ̀ⲧⲉ Ⲡⲉⲛϭⲟⲓⲥ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅.", 
"Salut à mes seigneurs♫ les pères apôtres♫ salut aux disciples de notre Seigneur Jésus-Christ.", 
"شيري ناتشويس إنيوتي♫ إن آبوسطولوس♫ شيري ني ماثيتيس♫ إنتي بينتشويس إيسوس بيخريستوس.", 
"السَّلامُ لساداتي♫ وآبائي الرسل♫ السَّلامُ، لتلاميذ، رَبّنا، يَسُوعْ المسيح.", 
],
],
[
[
Prefix.cymbalVerses+"StMarc&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲁⲕ ⲱ̀ ⲡⲓⲙⲁⲣⲧⲩⲣⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲉⲩⲁⲅⲅⲉⲗⲓⲥⲧⲏⲥ: ⲭⲉⲣⲉ ⲡⲓⲁ̀ⲡⲟⲥⲧⲟⲗⲟⲥ: Ⲙⲁⲣⲕⲟⲥ ⲡⲓⲑⲉⲱ̀ⲣⲓⲙⲟⲥ.", 
"Salut à toi martyr♫ salut à l'évangéliste♫ salut à l'apôtre♫ Marc le contemplateur de Dieu.", 
"شيري ناك أوبي مارتيروس♫ شيري بي إف آنجيلَيستيس♫ شيري بي أبوسطولوس♫ مارقوس بيثيؤريموس.", 
"السَّلامُ لَكَ أيُّهَا الشَهِيدْ، السَّلامُ♫ للإنجيلي♫ السَّلامُ، للرسول، مرقس ناظر الإله.", 
],
],
[
[
Prefix.cymbalVerses+"StSteven&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲥⲧⲉⲫⲁⲛⲟⲥ: ⲡⲓϣⲟⲣⲡ ⲙ̀ⲙⲁⲣⲧⲩⲣⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲁⲣⲭⲓⲇⲓⲁⲕⲱⲛ: ⲟⲩⲟϩ ⲧ̀ⲥ̀ⲙⲁⲣⲱⲟⲩⲧ.", 
"Salut à Etienne♫ Le premier martyrs♫ salut à l’archidiacre béni.", 
"شيري استيفانوس♫ بيشورَبّ إممارتيروس♫ شيري بي أرشيذياكون♫ أووه إت إسماروؤت.", 
"السَّلامُ لاسطفانوس♫ أول الشهداء♫ السَّلامُ لرئيس الشمامسة المبارك.", 
],
],
[
[
Prefix.cymbalVerses+"StGeorge&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲁⲕ ⲱ̀ ⲡⲓⲙⲁⲣⲧⲩⲣⲟⲥ: ⲭⲉⲣⲉ ⲡⲓϣⲱⲓϫ ⲛ̀ⲅⲉⲛⲛⲉⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲁⲑⲗⲟⲫⲟⲣⲟⲥ: ⲡⲁϭⲟⲓⲥ ⲡ̀ⲟⲩⲣⲟ Ⲅⲉⲱ̀ⲣⲅⲓⲟⲥ.", 
"Salut à toi ô martyr♫ salut au héros courageux♫ salut au persévérant♫ mon seigneur le roi Georges.", 
"شيري ناك أوبي مارتيروس♫ شيري بيشويج إن جينيؤوس♫ شيري بي آثلوفوروس؛ باشويس ابؤورو جاؤرجيوس.", 
"السَّلامُ لَكَ أيُّهَا الشَهِيدْ، السَّلامُ♫ للشجاع البطل♫ السَّلامُ للابس الجهاد، سيدي الملك، جؤرجيوس.", 
],
],
[
[
Prefix.cymbalVerses+"StTheodor&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲁⲕ ⲱ̀ ⲡⲓⲙⲁⲣⲧⲩⲣⲟⲥ: ⲭⲉⲣⲉ ⲡⲓϣⲱⲓϫ ⲛ̀ⲅⲉⲛⲛⲉⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲁⲑⲗⲟⲫⲟⲣⲟⲥ: Ⲑⲉⲟ̀ⲇⲱⲣⲟⲥ ⲡⲓⲥ̀ⲧⲣⲁⲧⲓⲗⲁⲧⲏⲥ.", 
"Salut à toi ô martyr♫ salut au héros courageux♫ salut au persévérant♫ Théodore le stratège.", 
"شيري ناك أوبي مارتيروس♫ شيري بيشويج إن جينيؤوس♫ شيري بي آثلوفوروس؛ ثيؤدوروس بي استراتيلاتيس.", 
"السَّلامُ لَكَ أيُّهَا الشَهِيدْ، السَّلامُ♫ للشجاع البطل♫ السَّلامُ للابس الجهاد♫ ثيؤدوروس، الأسفهسلار.", 
],
],
[
[
Prefix.cymbalVerses+"StMarcorious&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲁⲕ ⲱ̀ ⲡⲓⲙⲁⲣⲧⲩⲣⲟⲥ: ⲭⲉⲣⲉ ⲡⲓϣⲱⲓϫ ⲛ̀ⲅⲉⲛⲛⲉⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲁⲑⲗⲟⲫⲟⲣⲟⲥ: ⲫⲓⲗⲟⲡⲁⲧⲏⲣ Ⲙⲉⲣⲕⲟⲩⲣⲓⲟⲥ.", 
"Salut à toi ô martyr♫ salut au héros courageux♫ salut au persévérant, Philopatir Mercorios.", 
"شيري ناك أوبي مارتيروس♫ شيري بيشويج إن جينيؤوس♫ شيري بي آثلوفوروس؛ فيلوباتير مارقوريوس.", 
"السَّلامُ لَكَ أيُّهَا الشَهِيدْ، السَّلامُ♫ للشجاع البطل♫ السَّلامُ للابس الجهاد، فيلوباتير مرقوريوس.", 
],
],
[
[
Prefix.cymbalVerses+"StMina&D=$copticFeasts.AnyDay&C=Diacon", 
"Ⲭⲉⲣⲉ ⲛⲁⲕ ⲱ̀ ⲡⲓⲙⲁⲣⲧⲩⲣⲟⲥ: ⲭⲉⲣⲉ ⲡⲓϣⲱⲓϫ ⲛ̀ⲅⲉⲛⲛⲉⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲁⲑⲗⲟⲫⲟⲣⲟⲥ: ⲡⲓⲁ̀ⲅⲓⲟⲥ ⲁⲃⲃⲁ Ⲙⲏⲛⲁ.", 
"Salut à toi ô martyr♫ salut au héros courageux♫ salut au persévérant♫ abba Mina.", 
"شيري ناك أوبي مارتيروس♫ شيري بيشويج إن جينيؤوس♫ شيري بي آثلوفوروس؛ بي آجيوس آبا مينا.", 
"السَّلامُ لَكَ أيُّهَا الشَهِيدْ، السَّلامُ♫ للشجاع البطل♫ السَّلامُ للابس الجهاد، القديس آبا مينا.", 
],
],
[
[
Prefix.cymbalVerses+"End&D=$copticFeasts.AnyDay&C=Diacon", 
"Ϩⲓⲧⲉⲛ ⲛⲓⲡ̀ⲣⲉⲥⲃⲓⲁ: ⲛ̀ⲧⲉ ϯⲑⲉⲟ̀ⲧⲟⲕⲟⲥ ⲉⲑⲟⲩⲁⲃ Ⲙⲁⲣⲓⲁ: Ⲡ̀ϭⲟⲓⲥ ⲁ̀ⲣⲓϩ̀ⲙⲟⲧ ⲛⲁⲛ ⲙ̀ⲡⲓⲭⲱ ⲉ̀ⲃⲟⲗ ⲛ̀ⲧⲉ ⲛⲉⲛⲛⲟⲃⲓ.", 
"Par les intercessions de Sainte Marie♫ Mère de Dieu♫ Seigneur accorde nous la rémission de nos péchés.", 
"هيتن ني ابريسفيا♫ انتي تي ثيؤطوكوس اثؤواب ماريا♫ ابشويس آري إهموت نان امبي كو إيفول انتي ني نوفي.", 
"بِشَفَاعَاتْ والدة الإله♫ القِدِّيسَةْ مَرْيَمْ ♫ يا رَبّ انْعِمْ لنا بِمَغْفِرَةْ خَطَايَانَا.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲉⲑⲣⲉⲛϩⲱⲥ ⲉ̀ⲣⲟⲕ: ⲛⲉⲙ Ⲡⲉⲕⲓⲱⲧ ⲛ̀ⲁ̀ⲅⲁⲑⲟⲥ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ: ϫⲉ ⲁⲕ̀' ⲁⲕⲥⲱϯ ⲙ̀ⲙⲟⲛ ⲛⲁⲓ ⲛⲁⲛ.", 
"Afin que nous Te louions avec Ton Père très bon et le Saint Esprit♫ car Tu es venu et nous as sauvés .", 
"اثرين هوس♫إروك♫ نيم بيكيوت إن أغاثوس♫ نيم بي إبنيفما إثؤواب جي آك إي أكسوتي إمّون ناي نان.", 
"لكي نُسَبِحَكْ مَعَ، أبيك♫ الصَالِحْ والْرُوحْ القُدُسْ♫ لأنكَ أتيْتَ وخَلصْتَنا ارْحَمْنَا.", 
],
],
[
[
Prefix.cymbalVerses+"LordFeastsEnd&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Clôture des Quatrins du carillon pour les fêtes du Seigneur", 
"", 
"ختام أرَبّاع الناقوس في الأعياد السيدية", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲛ̀ⲥⲁϥ ⲛⲉⲙ ⲫⲟⲟ̀ⲩ: ⲛ̀ⲑⲟϥ ⲛ̀ⲑⲟϥ ⲡⲉ ⲛⲉⲙ ϣⲁ ⲉ̀ⲛⲉϩ: ϧⲉⲛ ⲟⲩϩⲩⲡⲟⲥⲧⲁⲥⲓⲥ ⲛ̀ⲟ̀ⲩⲱ̀ⲧ: ⲧⲉⲛⲟ̀ⲩⲱ̀ϣⲧ ⲙ̀ⲙⲟϥ ⲧⲉⲛϯⲱ̀ⲟ̀ⲩ ⲛⲁϥ.", 
"Jésus-Christ est Lui-même hier♫ aujourd’hui et éternellement♫ avec Son hypostase unique♫ Nous l’adorons et nous le glorifions.", 
"", 
"يَسُوعْ المَسِيحْ هو هو♫ أمس واليوم وإلي الأبد♫ بأُقنوم واحد♫ نسجد لَهُ ونمجده.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲡ̀ⲟⲩⲣⲟ ⲛ̀ⲧⲉ ϯϩⲓⲣⲏⲛⲏ: ⲙⲟⲓ ⲛⲁⲛ ⲛ̀ⲧⲉⲕϩⲓⲣⲏⲛⲏ ⲥⲉⲙⲛⲓ ⲛⲁⲛ ⲛ̀ⲧⲉⲕϩⲓⲣⲏⲛⲏ: ⲭⲁ ⲛⲉⲛⲛⲟⲃⲓ ⲛⲁⲛ ⲉ̀ⲃⲟⲗ.", 
"Ô Roi de la paix♫ donne-nous Ta paix♫ accorde-nous Ta paix et pardonne-nous nos péchés", 
"", 
"يا ملك السَّلامُ أعطنا سلامك♫ قرر لنا سلامك♫ واغْفِرْ لَنَا خَطَايَانَا.", 
],
[
Prefix.same+"&C=Diacon", 
"̀Ϫ̀ⲱⲣ ⲉ̀ⲃⲟⲗ ⲛ̀ⲛⲓϫⲁϫⲓ: ⲛ̀ⲧⲉ ϯⲉⲕⲕ̀ⲗⲏⲥⲓⲁ: ⲁⲣⲓⲥⲟⲃⲧ ⲉ̀ⲣⲟⲥ: ⲛ̀ⲛⲉⲥⲕⲓⲙ ϣⲁ ⲉ̀ⲛⲉϩ.", 
"Disperse les ennemis de l'Église. Fortifie-la ainsi♫ elle ne sera jamais ébranlée.", 
"", 
"فرق أعداء♫ الكنيسة♫ وحصنها فلا♫ تتزعزع إلي الابد.", 
],
[
Prefix.same+"&C=Diacon", 
"̀Ⲉ̀ⲙⲙⲁⲛⲟⲩⲏⲗ Ⲡⲉⲛⲛⲟⲩϯ: ϧⲉⲛ ⲧⲉⲛⲙⲏϯ ϯⲛⲟⲩ: ϧⲉⲛ ⲡ̀ⲱ̀ⲟⲩ ⲛ̀ⲧⲉ Ⲡⲉϥⲓⲱⲧ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ.", 
"Emmanuel notre Dieu♫ est maintenant parmi nous♫ avec la gloire de son Père♫ et du Saint Esprit.", 
"", 
"عمانوئيل إلهنا♫ في وسطنا الآن♫ بمجد أبيه♫ والْرُوحْ القُدُسْ.", 
],
[
Prefix.same+"&C=Diacon", 
"̀̀Ⲛ̀ⲧⲉϥⲥ̀ⲙⲟⲩ ⲉ̀ⲣⲟⲛ ⲧⲏⲣⲉⲛ: ⲛ̀ⲧⲉϥⲧⲟⲩⲃⲟ ⲛ̀ⲛⲉⲛϩⲏⲧ: ⲛ̀ⲧⲉϥⲧⲁⲗϭⲟ ⲛ̀ⲛⲓϣⲱⲛⲓ: ⲛ̀ⲧⲉ ⲛⲉⲛⲯⲩⲭⲏ ⲛⲉⲙ ⲛⲉⲛⲥⲱⲙⲁ.", 
"Qu’Il nous bénisse tous♫ Et purifie nos cœurs♫ guérisse les maladies♫ de nos âmes et nos corps", 
"", 
"ليباركنا كلنا♫ ويطهر قلوبنا♫ ويشفي أمراض♫ نفوسنا وأجسادنا.", 
],
[
Prefix.same+"&C=Diacon", 
"̀Ⲧ̀ⲉⲛⲟⲩⲱϣⲧ ⲙ̀ⲙⲟⲕ ⲱ̀ Ⲡⲭ̅ⲥ̅: ⲛⲉⲙ Ⲡⲉⲕⲓⲱⲧ ⲛ̀ⲁ̀ⲅⲁⲑⲟⲥ: ⲛⲉⲙ Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲉⲑⲟⲩⲁⲃ: ϫⲉ ⲁⲕ̀' ⲁⲕⲥⲱϯ ⲙ̀ⲙⲟⲛ.", 
"Nous T'adorons ô Christ♫ avec Ton Père très bon♫ et le Saint Esprit♫ car Tu es venu et nous as sauvés.", 
"", 
"نسجد لَكَ ايها المسيح♫ مَعَ ابيك الصالح♫ والْرُوحْ القُدُسْ♫ لأنكَ أتيْتَ وخَلصْتَنا.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.Nayrouz||$copticFeasts.Nayrouz&C=Title", 
"", 
"Quatrins du carillon pour le Nayrouz", 
"", 
" أرَبّاع الناقوس لعيد النيروز", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲥ̀ⲙⲟⲩ ⲉ̀ⲡⲓⲭ̀ⲗⲟⲙ ⲛ̀ⲧⲉ ϯⲣⲟⲙⲡⲓ: ϩⲓⲧⲉⲛ ⲧⲉⲕⲙⲉⲧⲭ̀ⲣⲏⲥⲧⲟⲥ Ⲡⲟ̅ⲥ̅: ⲛⲓⲁ̀ⲣⲱⲟⲩ ⲛⲉⲙ ⲛⲓⲙⲟⲩⲙⲓ: ⲛⲉⲙ ⲛⲓⲥⲓϯ ⲛⲉⲙ ⲛⲓⲕⲁⲣⲡⲟⲥ.", 
"Bénis Seigneur par Ta bonté♫ la couronne de cette année ;♫ Bénis les fleuves♫ les sources♫ les plantes♫ et les fruits.", 
"", 
"بارك إكليل هَذِهِ السنة♫ بصلاحك يا رَبّ. الِأنَّهُار و الينابيع♫ والزروع و الأثُمَّار.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.CrossFeast&C=Title", 
"", 
"Quatrins du carillon pour la fête de la Croix", 
"", 
" أرَبّاع الناقوس لعيد الصليب", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲝⲉⲣⲉ ⲡⲓⲥ̀ⲧⲁⲩⲣⲟⲥ: ⲉ̀ⲧⲁⲩⲉϣ ⲡⲁⲟ̅ⲥ̅ ⲉ̀ⲣⲟϥ: ⲭⲉⲣⲉ ⲡⲓⲙ̀ϩⲁⲩ: ⲉⲧⲁⲩ ⲭⲱ ⲙ̀ⲡⲉϥⲥⲱⲙⲁ ⲛ̀ϧⲏⲧϥ", 
"Salut à la croix♫ sur laquelle fut crucifié Mon Seigneur. Salut au tombeau♫ dans lequel fut placé son corps.", 
"", 
"السَّلامُ للصليب♫ الذي صلب عليه رَبّي♫ السَّلامُ للقبر♫ الذي وضع فيه جسده.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲡⲓⲥ̀ⲧⲁⲩⲣⲟⲥ ⲡⲉ ⲡⲉⲛϩⲟⲡⲗⲟⲛ: ⲡⲓⲥ̀ⲧⲁⲩⲣⲟⲥ ⲡⲉ ⲧⲉⲛϩⲉⲗⲡⲓⲥ: ⲡⲓⲥ̀ⲧⲁⲩⲣⲟⲥ ⲡⲉ ⲡⲉⲛⲧⲁϫⲣⲟ: ϧⲉⲛ ⲛⲉⲛϩⲟϫϩⲉϫ ⲛⲉⲙ ⲛⲉⲛⲑ̀ⲗⲓⲯⲓⲥ.", 
"La croix est notre arme♫ la croix est notre espérance♫ la croix est notre raffermissement♫ dans nos détresses et nos souffrances.", 
"", 
"الصليب هو سلاحنا♫ الصَلِيبْ هو رجاؤنا♫ الصَلِيبْ هو ثباتنا♫ في ضيقاتنا وشَدَائِدْنَا.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.Kiahk&C=Title", 
"", 
"Quatrins du carillon pour le mois de Kiahk", 
"", 
" أرَبّاع الناقوس لشهر كيهك", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲝⲉⲣⲉ Ⲅⲁⲃⲣⲓⲏⲗ: ⲡⲓⲛⲓϣϯ ⲛ̀ⲁⲣⲭⲓⲁⲅⲅⲉⲗⲟⲥ: ⲭⲉⲣⲉ ⲫⲏⲉⲧⲁϥϩⲓϣⲉⲛⲛⲟⲩϥⲓ: ⲙ̀Ⲙⲁⲣⲓⲁ ϯⲡⲁⲣⲑⲉⲛⲟⲥ.", 
"Salut à Gabriel♫ le grand archange♫ Salut à celui qui a♫ annoncé la Vierge Marie.", 
"", 
"السَّلامُ لغبريال♫ رئيس المَلائِكَةْ العظيم♫ السَّلامُ للذي بشر♫ مريم العذراء.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲓⲱⲁⲛⲛⲏⲥ ⲡⲓⲛⲓϣϯ ⲙ̀ⲡ̀ⲣⲟⲇⲣⲟⲙⲟⲥ ⲭⲉⲣⲉ ⲡⲓⲟ̀ⲩⲏⲃ ⲡ̀ⲥⲉⲅⲅⲉⲛⲏⲥ ⲛ̀Ⲉⲙⲙⲁⲛⲟⲩⲏ̀ⲗ", 
"Salut à Jean♫ le grand précurseur♫ salut au prêtre♫ parent d’Emmanuel.", 
"", 
"السَّلامُ ليوحنا♫ السابق العظيم♫ السَّلامُ للكاهن♫ نسيب عمانوئيل.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.NativityParamoun&C=Title", 
"", 
"Quatrins du carillon pour le Paramoun de la Nativité", 
"", 
" أرَبّاع الناقوس لبرامون عيد الميلاد", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲝⲉⲣⲉ Ⲅⲁⲃⲣⲓⲏⲗ: ⲡⲓⲛⲓϣϯ ⲛ̀ⲁⲣⲭⲓⲁⲅⲅⲉⲗⲟⲥ: ⲭⲉⲣⲉ ⲫⲏⲉⲧⲁϥϩⲓϣⲉⲛⲛⲟⲩϥⲓ: ⲙ̀Ⲙⲁⲣⲓⲁ ϯⲡⲁⲣⲑⲉⲛⲟⲥ.", 
"Salut à Gabriel♫ le grand archange♫ salut à celui qui a♫ annoncé Marie la vierge.", 
"", 
"السَّلامُ لغبريال♫ رئيس المَلائِكَةْ العظيم. السَّلامُ للذي بشر♫ مريم العذراء.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲱ ⲛⲓⲛⲁⲕϩⲓ ⲛ̀ⲛⲟⲩϯ: ⲟⲩⲟϩ ⲛ̀ϣⲟⲩⲉⲣϣ̀ⲫⲏⲣⲓ ⲙ̀ⲙⲱⲟⲩ: ⲛ̀ⲧⲉ ϯⲑⲉⲟ̀ⲧⲟⲕⲟⲥ Ⲙⲁⲣⲓⲁ: ⲉⲧⲟⲓ ⲙ̀ⲡⲁⲣⲑⲉⲛⲟⲥ ⲛ̀ⲥⲏⲟⲩ ⲛⲓⲃⲉⲛ.", 
"Ô merveille divine♫ la mère de Dieu♫ Marie la vierge♫ en tout temps.", 
"", 
"يا للطلقات الإلهية♫ المتعجب منها♫ التي لوالدة الإله♫ مريم العَذْراءْ كُلِّ حين.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.Nativity&C=Title", 
"", 
"Quatrins du carillon pour la Nativité", 
"", 
" أرَبّاع الناقوس لعيد الميلاد", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲡⲓϫⲓⲛⲙⲓⲥⲓ ⲙ̀ⲡⲁⲣⲑⲉⲛⲓⲕⲟⲛ: ⲟⲩⲟϩ ⲛⲓⲛⲁⲕϩⲓ ⲙ̀ⲡ̀ⲛⲁⲧⲓⲕⲟⲛ: ⲟⲩϣ̀ⲫⲏⲣⲓ ⲙ̀ⲡⲁⲣⲁⲇⲟⲝⲟⲛ: ⲕⲁⲧⲁ ⲛⲓⲥⲙⲓ ⲙ̀ⲡ̀ⲣⲟⲫⲏⲧⲓⲕⲟⲛ.", 
"Naissance virginale♫ et douleurs spirituelles♫ surprenant et glorieux♫ selon les prophètes.", 
"ايجين ميسى إم بارثينيكون: أووه نى ناكهى ام ابنفما تيكون: أو اشفيرى إمبارذوكسون كاتا نى إزمى إمبروفيتكون.", 
"ميلاد بتولي♫ وطلق روحي عجيب♫ ممجد♫ حسب الأخبار النبوية.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲃⲏⲑⲗⲉⲉⲙ: ⲧ̀ⲡⲟⲗⲓⲥ ⲛ̀ⲛⲓⲡ̀ⲣⲟⲫⲏⲧⲏⲥ: ⲑⲏⲉ̀ⲧⲁⲩⲙⲉⲥ Ⲡⲭ̅ⲥ̅ ⲛ̀ϧⲏⲧⲥ: ⲡⲓⲙⲁϩ ⲥ̀ⲛⲁⲩ ⲛ̀Ⲁⲇⲁⲙ.", 
"Salut à toi♫ Bethléem la ville des prophètes♫ où est né le Christ♫ le second Adam.", 
"شيرى فيثليئيم: إتبولَيس إن نى ابروفيتيس: ثيئيتاف ميس بخرستوس انخيتس: بى ماه اثناف ان آدام.", 
"السَّلامُ لبيت لحم♫ مدينة الأنبياء♫ التي ولد فيها♫ المَسِيحْ آدم الثاني.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.Circumcision&C=Title", 
"", 
"Quatrins du carillon pour la fête de la circomcision", 
"", 
"أرَبّاع الناقوس لعيد الختان", 
],
[
Prefix.same+"&C=Diacon", 
"Ϧⲉⲛ ⲡⲓⲙⲁϩ ϣ̀ⲙⲏⲛ ⲛ̀ⲉ̀ϩⲟⲟ̀ⲩ: ⲛ̀ⲧⲉ ⲡⲉϥϫⲓⲛⲙⲓⲥⲓ ⲙ̀ⲡⲁⲣⲁⲇⲟⲝⲟⲛ: ⲁϥϣⲱⲡ ⲉ̀ⲣⲟϥ ⲙ̀ⲡⲓⲥⲉⲃⲓ: ⲕⲁⲧⲁ ⲡⲉⲧⲥ̀ϣⲉ ⲙ̀ⲡⲓⲛⲟⲙⲟⲥ.", 
"Le huitième jour♫ de Sa naissance glorieuse♫ Il reçut la circoncision♫ selon la Loi.", 
"خين بى ماه إشمين إن إيهواوو♫ إنتى بيف ﭼين ميسى♫ إمباراذوكسون♫ أفشوب اروف امبيسيﭭى♫ كاطا بيت إس شى إمى نوموس .", 
"في اليوم الثامن♫ لميلاده المجيد♫ قبل إليه الختان♫ كعاده الناموس.", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"LordFeastsEnd&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.BaptismParamoun&C=Title", 
"", 
"Quatrins du carillon pour le paramoun du Baptême du Christ", 
"", 
" أرَبّاع الناقوس لبرامون الغطاس", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲝⲉⲣⲉ Ⲓⲱⲁⲛⲛⲑⲥ: ⲡⲓⲛⲓϣϯ ⲙⲡⲣⲟⲇⲣⲟⲙⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲟⲩⲑⲃ ⲡⲥⲉⲅⲅⲉⲛⲑⲥ ⲛⲈⲙⲙⲁⲛⲟⲩⲑⲗ", 
"Salut à Jean♫ le grand précurseur♫ salut au prêtre♫ parent d’Emmanuel.", 
"", 
"السَّلامُ ليوحنا♫ السابق العظيم♫ السَّلامُ للكاهن♫ نسيب عمانوئيل.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲣⲱϥ ⲙ̀Ⲫ̀ϯ ⲁϥⲉⲣⲙⲉⲑⲣⲉ: ϧⲁⲣⲟⲕ ⲱ̀ ⲡⲓⲣⲉϥϯⲟⲙⲥ: ϫⲉ ⲙ̀ⲙⲟⲛ ⲫⲏⲉⲧⲧⲉⲛⲑⲱⲛⲧ ⲉ̀ⲣⲟⲕ: ϧⲉⲛ ⲛⲓⲙⲓⲥⲓ ⲛ̀ⲧⲉ ⲛⲓϩⲓⲟⲙⲓ.", 
"La bouche de Dieu♫ l’a attesté ô Baptiste♫ « Nul ne te ressemble♫ parmi les nés d’une femme ».", 
"", 
"فم اللّه شهد لك♫ يا يوحنا المعمدان♫ لِأنَّهُ لَيْسَ من يشبهك♫ في مواليد النساء.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.Baptism&C=Title", 
"", 
"Quatrins du carillon pour le Baptême du Christ", 
"", 
" أرَبّاع الناقوس لعيد الغطاس", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲅⲉ ⲫⲁⲓ ⲡⲉ Ⲡⲁϣⲏⲣⲓ ⲡⲁⲙⲉⲛⲣⲓⲧ: ⲉ̀ⲧⲁ ⲧⲁⲯ̀ⲩⲭⲏ ϯⲙⲁϯ ⲛ̀ϧⲏⲧϥ: ϫⲉ ⲁϥⲉ̀ⲣⲡⲁⲟ̀ⲩⲱ̀ϣ ⲥⲱⲧⲉⲙ ⲛ̀ⲥⲱϥ: ϫⲉ ⲛ̀ⲑⲟϥ ⲡⲉ ⲡⲓⲣⲉϥⲧⲁⲛϧⲟ.", 
"Celui-ci est mon Fils bien-aimé♫ en qui j'ai mis tout mon amour♫ et qui a accompli ma volonté ;♫ écoutez-le car c’est Lui qui donne la vie.", 
"", 
"هذا هو إبني حبيبي♫ الذي سُرّت به نَفْسِي♫ وصنع مشيئتي♫ لَهُ اسمعوا لِأنَّهُ هو المحيي.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲑⲉⲗⲏⲗ ⲙ̀ⲫ̀ⲣⲏϯ ⲛ̀ϩⲁⲛϩⲓⲏⲃ: ⲱ ⲡⲓⲒⲟⲣⲇⲁⲛⲏⲥ ⲛⲉⲙ ⲡⲉϥⲇ̀ⲣⲓⲙⲟⲥ: ϫⲉ ⲁϥⲓ̀ ϣⲁⲣⲟⲕ ⲛ̀ϫⲉ ⲡⲓϩⲓⲏⲃ: ⲫⲏⲉ̀ⲧⲱⲗⲓ ⲙ̀ⲫ̀ⲛⲟⲃⲓ ⲙ̀ⲡⲓⲕⲟⲥⲙⲟⲥ", 
"Réjouis-toi comme les agneaux♫ ô Jourdain et ses rives♫ car c'est à toi qu’est venu l'Agneau♫ qui porte le péché du monde.", 
"", 
"تهلل مِثْلَ الحملان♫ أيُّهَا الاردن وبريته♫ فقد أتى إليَكَ الحمل♫ حامل خطية العالم.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲟⲩⲣⲁⲛ ⲛ̀ϣⲟⲩϣⲟⲩ ⲡⲉ ⲡⲉⲕⲣⲁⲛ: ⲱ̀ ⲡⲓⲥⲩⲅⲅⲉⲛⲏⲥ ⲛ̀Ⲉⲙⲙⲁⲛⲟⲩⲏ̀ⲗ: ⲛ̀ⲑⲟⲕ ⲟ̀ⲩⲛⲓϣϯ ϧⲉⲛ ⲛⲏⲉ̅ⲑ̅ⲩ̅ ⲧⲏⲣⲟⲩ: Ⲓⲱⲁⲛⲛⲏⲥ ⲡⲓⲣⲉϥϯⲱⲙⲥ.", 
"Un nom de fierté est ton nom♫ parent d’Emmanuel♫ tu es grand parmi tous les saints♫ ô Jean Baptiste.", 
"", 
"اسم فخر هو اسمك♫ يا نسيب عمانوئيل أنْتَ عظيم♫ في جَمِيعْ القِدِّيسِينْ♫ يا يوحنا المعمدان.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲓⲱⲁⲛⲛⲏⲥ: ⲡⲓⲛⲓϣϯ ⲙ̀ⲡ̀ⲣⲟⲇⲣⲟⲙⲟⲥ: ⲭⲉⲣⲉ ⲡⲓⲟ̀ⲩⲏⲃ: ⲡ̀ⲥⲉⲅⲅⲉⲛⲏⲥ ⲛ̀Ⲉⲙⲙⲁⲛⲟⲩⲏ̀ⲗ", 
"Salut à Jean le grand précurseur♫ salut au prêtre♫ parent d’Emmanuel.", 
"", 
"السَّلامُ ليوحنا♫ السابق العظيم♫ السَّلامُ للكاهن♫ نسيب عمانوئيل.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.CanaWedding&C=Title", 
"", 
"Quatrins du carillon pour les Noces de Cana", 
"", 
" أرَبّاع الناقوس لعرس قانا الجليل", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲥⲟⲟⲩ (ⲋ) ⲛ̀ϩⲩⲇⲣⲓⲁ̀ ⲙ̀ⲙⲱⲟⲩ: ⲉⲩⲏⲣⲡ ⲉϥⲥⲱⲧⲡ ⲁϥⲟⲩⲱ̀ⲧⲉⲃ ⲙ̀ⲙⲱⲟⲩ: ⲉ̀ⲃⲟⲗϩⲓⲧⲉⲛ ⲡⲉϥⲛⲓϣϯ ⲛ̀ⲱ̀ⲟⲩ: ⲡ̀ϩⲟⲡ ⲛ̀ⲧ̀Ⲕⲁⲛⲁ ⲛ̀ⲧⲉ ϯⲄⲁⲗⲓⲗⲉⲁ̀", 
"Six jarres d'eau♫ Il les a changées en vin exquis♫ avec Sa grande gloire♫ à Cana en Galilée.", 
"", 
"سته أجران ماء حولها♫ إلى خمر مختار♫ بمجده العظيم♫ في عرس قانا الجليل.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.EntryToTemple&C=Title", 
"", 
"Quatrins du carillon pour l’entrée du Christ au Temple", 
"", 
" أرَبّاع الناقوس لعيد دخول المَسِيحْ إلى الهَيْكَلْ", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲙⲉⲛⲉⲛⲥⲁ ϩ̀ⲙⲉ ⲛ̀ⲉ̀ϩⲟⲟⲩ: ⲛ̀ⲧⲉ ⲡⲉϥϫⲓⲛⲙⲓⲥⲓ: ⲙ̀ⲡⲁⲣⲁⲇⲟⲍⲟⲛ: ⲁϥϣⲉ ⲉ̀ϧⲟⲩⲛ ⲉ̀ⲡⲓⲉⲣⲫⲉⲓ.", 
"Après 40 jours♫ de sa glorieuse naissance♫ Il s’est présenté♫ au temple.", 
"", 
"بعد أرَبّعين يوماً♫ لميلاده العجيب♫ دخل♫ الهَيْكَلْ.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.GreatLent&C=Title", 
"", 
"Quatrins du carillon pour le Grand Carême", 
"", 
" أرَبّاع الناقوس للصوم الكبير", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁ̀ⲡⲉⲛⲟ̅ⲥ̅ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅: ⲉⲣⲛⲏⲥⲧⲉⲩⲓⲛ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ϫⲱⲛ: ⲛ̀ϩ̀ⲙⲉ ⲛ̀ⲉ̀ϩⲟⲟ̀ⲩ ⲛⲉⲙ ϩ̀ⲙⲉ ⲛ̀ⲉ̀ϫⲱⲣϩ: ϣⲁ ⲛ̀ⲧⲉϥⲥⲱⲧⲧⲉⲛ ϧⲉⲛ ⲛⲉⲛⲛⲟⲃⲓ.", 
"Notre Seigneur Jésus Christ♫ a jeûné Pour nous♫ quarante jours et nuits♫ pour nous sauver de nos péchés.", 
"", 
"رَبّنا يَسُوعْ المسيح♫ صام عنا♫ أرَبّعين يوماً وأرَبّعين ليلة♫ حتى خلصنا من خَطَايَانَا.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁⲛⲟⲛ ϩⲱⲛ ⲙⲁⲣⲉⲛ ⲉⲣⲛⲏⲥⲧⲉⲩⲓⲛ: ϧⲉⲛ ⲟ̀ⲩⲧⲟⲩⲃⲟ ⲛⲉⲙ ⲟ̀ⲩⲙⲉⲑⲙⲏⲓ: ⲟⲩⲟϩ ⲛ̀ⲧⲉⲛⲉ̀ⲣ ⲡ̀ⲣⲟⲥⲉ̀ⲩⲭⲉⲥⲑⲉ: ⲉⲛⲱ̀ϣ ⲉ̀ⲃⲟⲗ ⲉⲛϫⲱ ⲙ̀ⲙⲟⲥ", 
"Et nous aussi jeûnons♫ avec pureté et droiture♫ et prions en s’écriant♫ et en disant :", 
"", 
"ونحن أيضاً فلنصم♫ بطهارة وبر♫ ونصلي♫ صارخين قائلين:", 
],
[
Prefix.same+"&C=Diacon", 
"Ϫⲉ ⲡⲉⲛⲒⲱⲧ ⲉⲧϧⲉⲛ ⲛⲓⲫⲏⲟ̀ⲩⲓ:̀ ⲙⲁⲣⲉϥⲧⲟⲩⲃⲟ ⲛ̀ϫⲉ ⲡⲉⲕⲣⲁⲛ: ⲙⲁⲣⲉⲥⲓ ⲛ̀ϫⲉ ⲧⲉⲕⲙⲉⲧⲟ̀ⲩⲣⲟ: ϫⲉ ⲫⲱⲕ ⲡⲉ ⲡⲓⲱ̀ⲟ̀ⲩ ϣⲁ ⲛⲓⲉ̀ⲛⲉϩ", 
"Ô notre Père qui est aux cieux♫ que Ton Nom soit sanctifié♫ que Ton Règne vienne♫ car à Toi la gloire éternellement.", 
"", 
"أبَانَا الذي في السَّمَواتْ♫ ليَتَقَدَّسْ اسمك♫ لِيأتْ مَلَكُوتَكْ♫ لِأنَّ لَكَ المَجْدُ إلي الأبد.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.Annonciation&C=Title", 
"", 
"Quatrins du carillon pour la fête de l’Annonciation", 
"", 
" أرَبّاع الناقوس لعيد البشارة", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲝⲉⲣⲉ Ⲅⲁⲃⲣⲓⲏⲗ: ⲡⲓⲛⲓϣϯ ⲛ̀ⲁⲣⲭⲓⲁⲅⲅⲉⲗⲟⲥ: ⲭⲉⲣⲉ ⲫⲏⲉⲧⲁϥϩⲓϣⲉⲛⲛⲟⲩϥⲓ: ⲙ̀Ⲙⲁⲣⲓⲁ ϯⲡⲁⲣⲑⲉⲛⲟⲥ.", 
"Salut à Gabriel♫ le grand archange♫ Salut à celui qui a annoncé♫ la Vierge Marie.", 
"", 
"السَّلامُ لغبريال♫ رئيس المَلائِكَةْ العظيم♫ السَّلامُ للذي بشر♫ مريم العذراء.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ ⲑⲏⲉ̀ⲧⲁⲥϫⲉⲙ ϩ̀ⲙⲟⲧ: Ⲡ̀ϭⲟⲓⲥ ϣⲟⲡ ⲛⲉⲙⲉ: ⲭⲉⲣⲉ ⲑⲏⲉ̀ⲧⲁⲥϭⲓ ⲛ̀ⲧⲉⲛ ⲡⲓⲁⲅⲅⲉⲗⲟⲥ: ⲙ̀ⲫ̀ⲣⲁϣⲓ ⲙ̀ⲡⲓⲕⲟⲥⲙⲟⲥ.", 
"Salut à celle qui trouva grâce♫ Le Seigneur est avec toi ;♫ Salut à celle qui a reçu♫ de l’ange La joie du monde.", 
"", 
"السَّلامُ للتي وجدت نعمة♫ الرَبّ مَعَك. لسلام للتي قبلت♫ من المَلاكْ فرح العالم.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁϥⲣⲉⲕ ⲛⲓⲫⲏⲟⲩⲓ ⲛ̀ⲧⲉ ⲛⲓⲫⲏⲟⲩⲓ: ⲁϥⲓ̀ ⲉ̀ⲑ̀ⲙⲏⲧⲣⲁ ⲛ̀ϯⲡⲁⲣⲑⲉⲛⲟⲥ: ⲁϥⲉⲣⲣⲱⲙⲓ ⲙ̀ⲡⲉⲛⲣⲏϯ: ϣⲁⲧⲉⲛ ⲫ̀ⲛⲟⲃⲓ ⲙ̀ⲙⲁⲩⲁⲧϥ.", 
"Il fit trembler les cieux des cieux♫ et est venu dans le ventre de la vierge♫ Il est devenu homme comme nous♫ à l’exception du péché.", 
"", 
"طأطأ سماء السَّمَواتْ♫ وجاء إلى بطن العذراء♫ وصار إنساناً مثلنا♫ ما خلا الخطية وحدها.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.LazarusSaturday&C=Title", 
"", 
"Quatrins du carillon pour le Samedi de Lazare", 
"", 
" أرَبّاع الناقوس لسبت لعاز", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲝⲉⲣⲉ Ⲗⲁⲍⲁⲣⲟⲥ ⲫⲏⲉ̀ⲧⲁϥⲧⲱⲛⲟⲥϥ ⲙⲉⲛⲉⲛⲥⲁ ϥ̀ⲧⲟⲟⲩ ⲛ̀ⲉ̀ϩⲟⲟⲩ ⲙⲁⲧⲟⲩⲛⲟⲥ ⲡⲁϩⲏⲧ ⲡⲁⲟ̅ⲥ̅ Ⲓⲏ̅ⲥ̅ ⲫⲏⲉⲧⲁϥϧⲁⲑⲃⲉϥ ⲛ̀ϫⲉ ⲡⲓⲡⲉⲧϩⲱⲟⲩ", 
"Salut à Lazare qu'Il a♫ ressuscité après quatre jours♫ Seigneur Jésus ressuscite mon cœur♫ que le mal a tué.", 
"", 
"السَّلامُ للعازر الذي♫ أقامه بعد أرَبّعة أيام♫ أقم يا رَبّي يَسُوعْ♫ قَلْبِي الذي قتله الشرير.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.PalmSunday&C=Title", 
"", 
"Quatrins du carillon pour le Dimanche des Rameaux", 
"", 
" أرَبّاع الناقوس لأحد الشعانين", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲱⲥⲁⲛⲛⲁ ϧⲉⲛ ⲛⲏⲉⲧϭⲟⲥⲓ: ⲫⲁⲓ ⲡⲉ ⲡ̀ⲟⲩⲣⲟ ⲙ̀ⲡⲒⲥⲣⲁⲏⲗ: ϥ̀ⲥ̀ⲙⲁⲣⲱⲟⲩⲧ ⲛ̀ϫⲉ ⲫⲏⲉⲑⲛⲏⲟⲩ: ϧⲉⲛ ⲫ̀ⲣⲁⲛ ⲙ̀Ⲡⲟ̅ⲥ̅ ⲛ̀ⲧⲉ ⲛⲓϫⲟⲙ", 
"Hosanna au plus haut des cieux♫ voici le Roi d'Israël♫ béni soit celui qui vient au nom♫ du Seigneur des puissances.", 
"", 
"أوصنا في الأعالي♫ هَذا هو ملك إسرائيل. مُبَارَكْ الآتي♫ باسم رَبّ القوات.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲫⲏⲉⲧϩⲉⲙⲥⲓ ϩⲓϫⲉⲛ ⲛⲓⲬⲉⲣⲟⲩⲃⲓⲙ: ⲁϥⲧⲁⲗⲟϥ ⲉ̀ⲟⲩⲉ̀ⲱ̀: ⲁϥϣⲉ ⲉ̀ϧⲟⲩⲛ ⲉ̀Ⲓⲉⲣⲟⲩⲥⲁⲗⲏⲙ: ⲟⲩⲡⲉ ⲡⲁⲓⲛⲓϣϯ ⲛ̀ⲑⲉⲃⲓⲟ̀.", 
"Celui qui siège au-dessus des chérubins♫ est monté sur un ânon♫ et Il est entré à Jérusalem ;♫ Quelle grande humilité!", 
"", 
"الجالس على الشاروبيم♫ ركب على أتان♫ ودخل إلى أورشليم♫ ما هو هَذا التواضع العظيم.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$Seasons.PentecostalDays&C=Title", 
"", 
"Quatrins du carillon pour la fête de la Résurrection", 
"", 
" أرَبّاع الناقوس للقيامة والخماسين", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁ Ⲡ̀Ϯⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ: ⲧⲱⲛϥ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ: ⲛ̀ⲑⲟϥ ⲡⲉ ⲧ̀Ϯ̀ⲁ̀ⲡⲁⲣⲭⲏ: ⲛ̀ⲧⲉ ⲛⲏⲉ̀ⲧⲁⲩⲉ̀ⲛⲕⲟⲧ.", 
"Le Christ notre Dieu est ressuscité♫ d’entre les morts♫ il est le premier♫ parmi les convives.", 
"", 
"المَسِيحْ إلهنا♫ قام من الأموات♫ وهو باكورة الراقدين.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲧⲉϥⲁ̀ⲛⲁⲥⲧⲁⲥⲓⲥ: ⲉ̀ⲧⲁϥⲧⲱⲛϥ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ: ϣⲁⲛ̀ⲧⲉϥⲥⲱϯ ⲙ̀ⲙⲟⲛ: ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲉⲛⲛⲟⲃⲓ.", 
"Salut à sa Résurrection♫ d’entre les morts♫ pour nous sauver♫ de nos péchés.", 
"", 
"السَّلامُ لقيامته♫ لما قام من بين الأموات♫ حتى خلصنا من خَطَايَانَا.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲗⲟⲓⲡⲟⲛ ⲁⲩⲭⲁϥ ϧⲉⲛ ⲡⲓⲙ̀ϩⲁⲩ: ⲕⲁⲧⲁ ⲛⲓⲥ̀ⲙⲏ ⲙ̀ⲡ̀ⲣⲟⲫⲏⲧⲓⲕⲟⲛ: ϧⲉⲛ ⲡⲓⲙⲁϩ ϣⲟⲙⲧ ⲛ̀ⲉ̀ϩⲟⲟⲩ: Ⲡⲭ̅ⲥ̅ ⲁ̀ⲛⲉⲥⲧⲏ ⲉⲕⲛⲉⲕⲣⲱⲛ.", 
"Il fut aussi placé au tombeau♫ selon les paroles et les prophétiques♫ et le troisième jour le Christ♫ est ressuscité d’entre les morts.", 
"", 
"وأيضا وُضع في القبر♫ حسب الأخبار النبوية♫ وفي اليوم الثَالِثْ المَسِيحْ قام من الأموات.", 
],
],
[
[
Prefix.cymbalVerses+"StMaykel&D=$Seasons.PentecostalDays&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲙⲓⲭⲁⲏⲗ: ⲡⲓⲛⲓϣϯ ⲛ̀ⲁⲣⲭⲓⲁⲅⲅⲉⲗⲟⲥ: ⲡⲓⲭ̀ⲣⲓⲙⲁⲛ ⲛ̀ⲟⲩϫⲁⲓ: ⲛ̀ⲧⲉ ϯⲁ̀ⲛⲁⲥⲧⲁⲥⲓⲥ.", 
"Salut à Michel le chef des archanges celui qui a annoncé le salut obtenu grâce à la Résurrection.", 
"", 
"السَّلامُ لميخائيل♫ رئيس المَلائِكَةْ العظيم♫ المنادي بالخلاص الذي للقيامة.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.Ascension&C=Title", 
"", 
"Quatrins du carillon pour la fête de l’Ascension", 
"", 
" أرَبّاع الناقوس لعيد الصعود", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁ Ⲡ̀Ϯⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ: ⲧⲱⲛϥ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ: ⲟⲩⲟϩ ⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ: ⲁϥϩⲉⲙⲥⲓ ⲥⲁⲟⲩⲓⲛⲁⲙ ⲙ̀Ⲡⲉϥⲓⲱⲧ", 
"Le Christ notre Dieu est ressuscité♫ des morts et est monté aux cieux♫ et S’est assis♫ à la droite de Son Père.", 
"", 
"المَسِيحْ إلَهْنَا قام من بين الأموات♫ وصعد إلى السَّمَواتْ♫ وجلس عن يمين أبيه.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ ⲧⲉϥⲁ̀ⲛⲁⲗⲩⲙⲯⲓⲥ: ⲉ̀ⲧⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ: ϧⲉⲛ ⲟⲩⲱ̀ⲟⲩ ⲛⲉⲙ ⲟⲩⲧⲁⲓⲟ: ⲁϥϩⲉⲙⲥⲓ ⲥⲁⲟⲩⲓⲛⲁⲙ ⲙ̀Ⲡⲉϥⲓⲱⲧ.", 
"Salut à son Ascension♫ quand il est monté aux cieux♫ avec gloire et honneur♫ Il s’est assis à la droite de Son Père.", 
"", 
"السَّلامُ لصعوده♫ لما صعد إلى السَّمَواتْ♫ بمجد وإكرام جلس عن يمين أبيه.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲧ̀ⲫⲉ: ⲛ̀ⲧⲉ ⲧ̀ⲫⲉ ⲥⲁ ⲛⲓⲙⲁⲛ̀ϣⲁⲓ: ϩⲓⲛⲁ ⲛ̀ⲧⲉϥⲟⲩⲱⲣⲡ ⲛⲁⲛ ⲙ̀ⲡⲓⲡⲁⲣⲁⲕⲗⲏⲧⲟⲛ: Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲛ̀ⲧⲉ ϯⲙⲉⲑⲙⲏⲓ.", 
"Il est monté aux cieux des cieux♫ vers l'orient pour nous envoyer♫ le Paraclet♫ l'Esprit de vérité.", 
"", 
"صعد إلى سماء السَّمَاء♫ ناحية المشارق لكي♫ يرسل لنا المعزي روح الحق.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.Pentecoste&C=Title", 
"", 
"Quatrins du carillon pour la fête de Pentecote", 
"", 
" أرَبّاع الناقوس لعيد العنصرة", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲁ Ⲡ̀Ϯⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ: ⲧⲱⲛϥ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ: ⲟⲩⲟϩ ⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ: ⲁϥⲟⲩⲱⲣⲡ ⲛⲁⲛ ⲙ̀ⲡⲓⲡⲁⲣⲁⲕⲗⲏⲧⲟⲛ", 
"Le Christ notre Dieu♫ est ressuscité des morts♫ et est monté aux cieux♫ et nous a envoyé le Consolateur.", 
"", 
"المَسِيحْ إلهنا♫ قام من بين الأموات♫ وصعد إلى السَّمَواتْ وأرسل لنا المعزي.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲭⲉⲣⲉ Ⲧⲉϥⲁ̀ⲛⲁⲗⲩⲙⲯⲓⲥ: ⲉ̀ⲧⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ: ⲁϥⲟⲩⲱⲣⲡ ⲛⲁⲛ ⲙ̀ⲡⲓⲡⲁⲣⲁⲕⲗⲏⲧⲟⲛ: Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲛ̀ⲧⲉ ϯⲙⲉⲑⲙⲏⲓ.", 
"Salut à son Ascension♫ quand il est monté aux cieux♫ et nous a envoyé le Consolateur♫ l’Esprit de vérité.", 
"", 
"السَّلامُ لصعوده♫ لما صعد إلى السَّمَواتْ♫ وأرسل لنا المعزي روح الحق.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲙ̀ⲡⲁⲣⲁⲕⲗⲏⲧⲟⲛ: ⲉ̀ⲧⲁϥⲓ̀ ⲉ̀ⲡⲉⲥⲏⲧ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲧ̀ⲫⲉ: ⲁϥⲫⲱⲣϣ ⲉ̀ϫⲉⲛ ⲫ̀ⲟⲩⲁⲓ ⲫ̀ⲟⲩⲁⲓ: ⲁⲩⲥⲁϫⲓ ϧⲉⲛ ϩⲁⲛⲙⲏϣ ⲛ̀ⲗⲁⲥ.", 
"Quand l'Esprit le Consolateur♫ est descendu du ciel♫ il s’est étendu sur chacun♫ ils ont parlé beaucoup de langues.", 
"", 
"الروح المعزى لما نزل من السَّمَاء♫ انبسط على كُلِّ واحد فواحد♫ فنطقوا بألسنة كثيرة.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.EntryToEgypt&C=Title", 
"", 
"Quatrins du carillon pour la fête de l’entrée du Christ en Egypte", 
"", 
" أرَبّاع لعيد دخول المَسِيحْ أرض مصر", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲣⲁϣⲓ ⲑⲉⲗⲏⲗ ⲱ̀ ⲭⲏⲙⲓ: ⲛⲉⲙ ⲛⲉⲥⲑⲱϣ ⲧⲏⲣⲟⲩ: ϫⲉ ⲁϥⲓ̀ ϣⲁⲣⲟ ⲛ̀ϫⲉ ⲡⲓⲙⲁⲓⲣⲱⲙⲓ: ⲫⲏⲉⲧϣⲟⲡ ϧⲁϫⲱⲟⲩ ⲛ̀ⲛⲓⲉ̀ⲱⲛ ⲧⲏⲣⲟⲩ.", 
"Réjouis-toi et sois heureuse♫ Ô l'Égypte et tous tes enfants et contrées♫ car l’ami du genre humain t’as visité♫ Lui qui existe avant tous les temps.", 
"", 
"افرحى وتهللي يا مصر♫ مَعَ بنيها وكُلَّ تخومها♫ لِأنَّهُ أتى إليَكَ مُحِبْ البشر♫ الكائن قبل كُلِّ الده ور.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲧⲉⲛⲟⲩⲱϣⲧ ⲙ̀ⲙⲟϥ ⲛ̀ⲧⲉϥⲉⲣϩ̀ⲙⲟⲧ ⲛⲁⲛ: ⲛ̀ⲟⲩⲙⲉⲧϣ̀ⲫⲏⲣ ⲛⲉⲙ ⲛⲓⲁ̀ⲗⲱⲟⲩⲓ̀: ⲉ̀ⲧⲁϥϧⲟⲑⲃⲟⲩ ⲛ̀ϫⲉ Ⲏⲣⲱⲇⲏⲥ: ϧⲉⲛ ⲡⲓⲉ̀ϩⲟⲟⲩ ⲛ̀ϯⲕ̀ⲣⲓⲥⲏⲥ.", 
"Nous nous prosternons devant Lui♫ afin qu’Il nous accorde♫ une place le jour du jugement♫ avec les enfants qu’a tué Hérode.", 
"", 
"نسجد لَهُ لكي ينعم♫ لنا بنصيب مَعَ الأطفال♫ الذين قتلهم هيرودس♫ في يوم الدينونة.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.Epiphany&C=Title", 
"", 
"Quatrins du carillon pour la fête de l’Épiphanie", 
"", 
" أرَبّاع الناقوس لعيد التجلي", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ Ⲡⲉⲛⲛⲟⲩϯ: ⲁϥϭⲓ ⲛ̀ⲛⲉϥⲙⲁⲑⲏⲧⲏⲥ: ⲁϥϭⲓⲧⲟⲩ ⲥⲁⲡ̀ϣⲱⲓ: ⲙ̀ⲡⲓⲧⲱⲟⲩ ⲛ̀Ⲑⲁⲃⲱⲣ.", 
"Jésus Christ notre Dieu♫ a pris Ses disciples♫ Il les a fait monter♫ sur le mont Thabor.", 
"", 
"يَسُوعْ المَسِيحْ إلهنا♫ أخذ تلاميذه♫ وأصعدهم♫ فوق جبل طابور.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲏⲗⲓⲁⲥ ⲛⲉⲙ Ⲙⲱⲩ̀ⲥⲏⲥ ⲡⲉⲧϫⲱⲣ: ⲁⲩⲛⲁⲩ ⲉ̀ⲛⲉϥϩ̀ⲃⲱⲥ ϩⲓ Ⲑⲁⲃⲱⲣ: ⲛⲓⲙⲁⲑⲏⲧⲏⲥ ⲉⲩⲉⲣϫⲓⲛⲓⲟⲣ: ⲛ̀ⲟⲩϭⲏⲡⲓ ⲉⲥⲉⲣⲟⲩⲱⲓⲛⲓ.", 
"Elie et Moïse les forts♫ ont vu Ses vêtements sur Thabor♫ les disciples sont passes♫ par un nuage brillant.", 
"", 
"إيليا وموسى القويان♫ نظرا ثيابه على طابور♫ التلاميذ عُبِّروا في♫ سحابة منيرة.", 
],
],
[
[
Prefix.cymbalVerses+"&D=$copticFeasts.Coptic29th&C=Title", 
"", 
"Quatrins du carillon pour le 29 du mois copte", 
"", 
" أرَبّاع الناقوس ليوم 29 من الشهر القبطي", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"&D=$copticFeasts.Annonciation", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"&D=$Seasons.Nativity", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"&D=$Seasons.PentecostalDays", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMary&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMaykel&D=$Seasons.PentecostalDays", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"SheroubimSerafim&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StJohnBaptist&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"Apostles&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMarc&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StSteven&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StGeorge&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StTheodor&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMarcorious&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"StMina&D=$copticFeasts.AnyDay", 
],
[
Prefix.placeHolder, 
Prefix.cymbalVerses+"LordFeastsEnd&D=$copticFeasts.AnyDay", 
],
],
[
[
Prefix.cymbalVerses+"PopeAndBishops&D=$copticFeasts.AnyDay&C=Title", 
"", 
"Quatrins du carillon en présence du Pape ou d’un Evêque", 
"", 
" أرَبّاع الناقوس في حضور البطرك أو الأسقف", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲧⲉⲛϯϩⲟ ⲉ̀ⲣⲟⲕ ⲱ̀ Ⲩ̀ⲓⲟⲥ Ⲑⲉⲟⲥ: ⲉⲑⲣⲉⲕⲁ̀ⲣⲉϩ ⲉ̀ⲡ̀ⲱⲛϧ ⲙ̀ⲡⲉⲛⲡⲁⲧⲣⲓⲁⲣⲭⲏⲥ: ⲡⲁⲡⲁ ⲁⲃⲃⲁ Ⲧⲁⲱⲁⲇⲣⲟⲥ ⲡⲓⲁⲣⲭⲓⲉ̀ⲣⲉⲩⲥ: ⲙⲁⲧⲁϫⲣⲟϥ ϩⲓϫⲉⲛ ⲡⲉϥⲑ̀ⲣⲟⲛⲟⲥ.", 
"Nous t’implorons♫ ô Fils de Dieu♫ de conserver la vie de notre patriarche♫ le grand prêtre anba Tawadros ;♫ maintiens-le sur son trône.", 
"", 
"نسألك يا أبن اللّه♫ أنْ تحفظ حياة♫ بطريركنا البابا أنبا تاوضروس رئيس الكهنة♫ ثبته علي كرسيه.", 
],
[
Prefix.same+"&C=Diacon", 
"Ⲛⲉⲙ ⲡⲉϥⲕⲉϣ̀ⲫⲏⲣ ⲛ̀ⲗⲓⲧⲟⲩⲣⲅⲟⲥ ⲡⲉⲛⲓⲱⲧ ⲉⲑⲟⲩⲁⲃ ⲛ̀ⲇⲓⲕⲉⲟⲥ: ⲁⲃⲃⲁ (…) ⲡⲓⲉ̀ⲡⲓⲥⲕⲟⲡⲟⲥ: ⲙⲁⲧⲁϫⲣⲟϥ ϩⲓϫⲉⲛ ⲡⲉϥⲑ̀ⲣⲟⲛⲟⲥ.", 
"Et son partenaire dans le ministère♫ notre père le juste anba (…) l'évêque ;♫ maintiens-le sur son siège.", 
"", 
"وشَريكَهُ في الخدمة♫ ابانا القديس البار♫ أنبا (...) الاسقف♫ ثبته علي كرسيه.", 
],
],
];